### ISSUE TITLE
theme_nothing() still has margins

### ISSUE THREAD

**Issue by ideamotor** [dkahle/ggmap#100]
Thoughts on how to remove these margins? Thanks.

```r
legendData <- c(100, 325, 550, 775, 1000)
legendColors <- c("#FF9DEB", "#9FC5FF", "#00E4D0", "#AAD44D", "#FFAE85")
df <- data.frame(x = legendData, col = legendColors, y = 1:5, stringsAsFactors = FALSE)
ggplot(df, aes(y = 1, x = x, fill = col)) + geom_tile() + 
    scale_fill_identity() + theme_nothing()
```
[gives me this](https://imgur.com/6DakXBf)

which is the same as this (but you can't see the margins with white background):

![rplot](https://cloud.githubusercontent.com/assets/1654283/16436163/304b24ac-3d61-11e6-9ff6-fbb3740c95d3.png)

**Comment by restonslacker** [comment]
I'm not sure that this as a ggmap issue.  It seems to be more of a general ggplot2 question.  You would probably have better luck asking at stackoverflow.com or on the ggplot2 mailing list https://groups.google.com/forum/#!forum/ggplot2

**Comment by dkahle** [comment]
I think this works properly, actually; let me know if I'm wrong.  It's a scale issue, not a margins issue. It think you just need to change the expanding in the x and y axis scales:
```r
legendData <- c(100, 325, 550, 775, 1000)
legendColors <- c("#FF9DEB", "#9FC5FF", "#00E4D0", "#AAD44D", "#FFAE85")
df <- data.frame(x = legendData, col = legendColors, y = 1:5, stringsAsFactors = FALSE)
ggplot(df, aes(y = 1, x = x, fill = col)) + geom_tile() + 
    scale_fill_identity() + theme_nothing() +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(expand = c(0,0))
```
There's another example in the documentation for `theme_nothing()`.
