### ISSUE TITLE
Cannot install on Ubuntu 14.06

### ISSUE THREAD

**Issue by thiagosfsilva** [dkahle/ggmap#101]
Tried to install ggmap on R 3.3.1 running on a Ubuntu 14.06 machine, from CRAN (install.packages), and first got this error:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/thiago/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so':
  libicui18n.so.52: cannot open shared object file: No such file or directory

I figured out that newer versions of Ubuntu use libicu55 instead of 52, so I created a symlink from  libicui18n.so.52 to libicui18n.so.55. 

The I tried to install from CRAN again (and later from GitHub), and got the same error message on both cases:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/thiago/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so':
  /home/thiago/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so: undefined symbol: _ZTIN6icu_528ByteSinkE
ERROR: lazy loading failed for package ‘ggmap’

Any suggestions to solve the issue are appreciated, thank you.

**Comment by dkahle** [comment]
Did you try re-installing stringi? Seems like the problem is with that package.

**Comment by thiagosfsilva** [comment]
That solved the issue. Sorry for what must have been a dumb question. Long time Windows user recently migrated to Linux here :-).

**Comment by dkahle** [comment]
No worries, glad it worked!
