### ISSUE TITLE
stamen returning .png's, not .jpg's

### ISSUE THREAD

**Issue by dkahle** [dkahle/ggmap#102]
```r
library(ggmap)
bbox <- c(left = -97.132, bottom = 31.536, right = -97.105, top = 31.560)
ggmap(get_stamenmap(bbox, zoom = 13))
```

submitted by Tom Faulhaber via twitter

**Comment by simonkth** [comment]
This is because of this part of the code (function `get_stamenmap`)

`  # set image type (stamen only)
  if(maptype %in% c("terrain","terrain-background","watercolor")){
    filetype <- "jpg"
  } else {
    filetype <- "png"
}`

--> terrain and terrain-background should be PNGs. As a temporary fix, you can make your own function.
