### ISSUE TITLE
geocode() returns the wrong coordinates when the address contains an ampersand

### ISSUE THREAD

**Issue by casa-henrym** [dkahle/ggmap#104]
The issue appears to be that the address is not URL-encoded prior to being sent to Google.

The built-in URLencode() function is not vectorised so the work-around is slightly clunky:
`geocode(sapply(Addresses, URLencode, reserved = TRUE))`

The "reserved = TRUE" flag is important as ampersand is not encoded if this is left at the default "FALSE".

**Comment by dkahle** [comment]
Changing
```r
url_string <- URLencode(url_string)
```
to 
```r
url_string <- vapply(url_string, URLencode, character(1), reserved = FALSE)
```
doesn't seem to work, I get the error 
```r
geocode("houston texas")
## Information from URL : http%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fgeocode%2Fjson%3Faddress%3Dhouston%20texas%26sensor%3Dfalse
## Error in url(url_string) : URL scheme unsupported by this method
```
Am I missing something here?

**Comment by casa-henrym** [comment]
From what I can see the R file [connections.c](http://docs.rexamine.com/R-devel/connections_8c_source.html) looks at the characters that make up the url to determine what type of connection this is (starting at line 5077). By URL-encoding the full URL, as you have done, you are replacing the all-important colon and slash characters that `connections.c` is looking for.

The only part of the URL I was encoding was the "location" parameter to `geocode()`. The invocation of `URLencode()` that you are referring to, within `geocode()`, will (as I have been using it) see that the `url_string` is already URLencoded (even if only partly-so) and return it unchanged (this behaviour can be changed by passing `repeated = TRUE` to `URLencode()`).

I haven't tried this myself but I would think that changing this line:
> location4url <- chartr(" ", "+", location)
to this:
> location4url <- URLencode(location, reserved = TRUE)
would fix my issue. The [HTML specification](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) will accept `+` or `%20` for a space, so `URLencode()` is a direct replacement for this `chartr()` call.

Note that the later invocation of `URLencode()` - the one you have changed - will still return the input as-is due to the aforementioned detection of existing URL-encoding within the input. If other parameters in the URL need to be URL encoded then this probably needs to be handled in separate invocations of `URLencode()`.

**Comment by dkahle** [comment]
I think I got it, thanks!  Let me know if I need to fix something.
