### ISSUE TITLE
mutate_geocode doesn't work with class tbl

### ISSUE THREAD

**Issue by voxnonecho** [dkahle/ggmap#106]
Minimal reproducible example:

```
addr_df <- tibble::data_frame(
  address = c("1600 Pennsylvania Avenue, Washington DC", "", "houston texas")
  )
```

We verify `address` is a character:

```
> str(addr_df)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	3 obs. of  1 variable:
 $ address: chr  "1600 Pennsylvania Avenue, Washington DC" "" "houston texas"
            ^^^
```

Gives:

```
> mutate_geocode(addr_df, address)
Error: is.character(location) is not TRUE
In addition: Warning message:
drop ignored 
```

Works fine when using `data.frame` and `stringsAsFactor = FALSE`:

**Comment by taraskaduk** [comment]
This issue was closed, yet I still have this issue. I'm new to Github, so please don't be angry with me - how do I see the solution or the fix?
Thank you!

**Comment by mvkorpel** [comment]
@taraskaduk You may try installing the GitHub (development) version of `ggmap`, This issue should be fixed there. The installation instructions are at the bottom of the front page (`README.md`),
