### ISSUE TITLE
ggplot2_2.1.0.9000 - Error in zero_range(from) : x must be length 1 or 2

### ISSUE THREAD

**Issue by titaniumtroop** [dkahle/ggmap#109]
Attempting to use ggplot2_2.1.0.9000 gives the subject error. Code works with CRAN version of ggplot2 (2.1.0).

Code:

```{r}
library(ggplot2) # ggplot2_2.1.0.9000
library(ggmap) # ggmap_2.6.1
lat <- as.numeric("34.807085")
lng <- as.numeric("-92.233561")
gmap <- get_map(location = c(lon = lng, lat = lat), zoom = 7, maptype = 'roadmap', scale=2, color = "bw") 
# Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=34.807085,-92.233561&zoom=7&size=640x640&scale=2&maptype=roadmap&language=en-EN&sensor=false
map <- ggmap(gmap)
map 
# Error in zero_range(from) : x must be length 1 or 2
```

**Comment by titaniumtroop** [comment]
I submitted this same bug report to the ggplot2 repository and received this response:

> There have been quite a lot of internal changes which are bound to have an effect on some of packages that extend ggplot2. Please report this to ggmap so they can look into it.

**Comment by dkahle** [comment]
This runs fine for me, have you tried installing the dev version?
```{r}
devtools::install_github("dkahle/ggmap")
```

**Comment by titaniumtroop** [comment]
I confirmed the issues is resolved with the dev version of ggmap. Should've tried that first. Thanks for the response.

**Comment by dkahle** [comment]
No problem, thanks!
