### ISSUE TITLE
get_map error in readPNG

### ISSUE THREAD

**Issue by rinks2511** [dkahle/ggmap#110]
I am running the following command -

chicago=get_map(location="chicago",zoom=11)

But i am getting the following error -

Map from URL : http://maps.googleapis.com/maps/api/staticmap?center=chicago&zoom=11&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false
Error in readPNG(tmp) : file is not in PNG format
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  download had nonzero exit statusMap from URL : http://maps.googleapis.com/maps/api/staticmap?center=chicago&zoom=11&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false
Error in readPNG(tmp) : file is not in PNG format
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  download had nonzero exit status

How can I resolve this?

**Comment by dkahle** [comment]
```{r}
devtools::install_github("dkahle/ggmap")
```
then re-try.
