### ISSUE TITLE
Error: GeomRasterAnn was built with an incompatible version of ggproto

### ISSUE THREAD

**Issue by neilfws** [dkahle/ggmap#122]
I'm using:
ggmap 2.6.1
ggplot2 2.2.0
R 3.3.2
macOS Sierra 10.12.1

```
library(ggmap)
NZ.map <- get_map(location = "New Zealand", zoom = 6, color = "bw")
p <- ggmap(NZ.map)

Error: GeomRasterAnn was built with an incompatible version of ggproto.
Please reinstall the package that provides this extension.
```

I believe the issue lies with ggplot2 rather than ggmap, but just wondered if you had any ideas as to a fix.

**Comment by mvkorpel** [comment]
Try reinstalling ggmap. In ggplot2 2.2.0 [news](https://cran.r-project.org/web/packages/ggplot2/news.html):

> Unfortunately there was a major oversight in the construction of ggproto which lead to extensions capturing the super object at package build time, instead of at package run time ([#1826](https://github.com/tidyverse/ggplot2/issues/1826)). This problem has been fixed, but requires re-installation of all extension packages.

**Comment by neilfws** [comment]
Thanks @mvkorpel - I have tried reinstalling ggmap (and ggplot2) several times, but still get the error. Perhaps I need to try build from source rather than the pre-built package?

**Comment by neilfws** [comment]
I've reinstalled ggmap from github instead of CRAN (version 2.6.2) and the error has gone. Thanks for your help.
