### ISSUE TITLE
"GeomRasterAnn was built with an incompatible version of ggproto."

### ISSUE THREAD

**Issue by Einfalt** [dkahle/ggmap#135]
On MacOS Sierra v.10.12 

seems to be a problem with ggplot2

http://stackoverflow.com/questions/40642850/ggmap-error-geomrasterann-was-built-with-an-incompatible-version-of-ggproto

**Comment by dkahle** [comment]
You need to install the dev version of __ggmap__:
```r
devtools::install_github("dkahle/ggmap")
```
