### ISSUE TITLE
geocode not working

### ISSUE THREAD

**Issue by kishensurajp** [dkahle/ggmap#140]
> geocode('hauz+khas,delhi')
Information from URL : http://maps.googleapis.com/maps/api/geocode/json?address=hauz+khas,delhi&sensor=false
  lon lat
1  NA  NA
Warning messages:
1: In readLines(connect, warn = FALSE) :
  unable to connect to 'maps.googleapis.com' on port 80.
2: In geocode("hauz+khas,delhi") :
    geocoding failed for "hauz+khas,delhi".
  if accompanied by 500 Internal Server Error with using dsk, try google.

ggmap version - 2.6.1

**Comment by bbrewington** [comment]
I'm running ggmap version 2.6.1 and was able to get that to work fine.  Try copy+pasting the url into a browser, and see if it works (to test whether you can access the raw response from Google Maps API)

**Comment by bbrewington** [comment]
If my above suggestion doesn't work, try the code below, and copy + paste the console output:

```r
library(httr)
r <- GET("http://maps.googleapis.com/maps/api/geocode/json?address=hauz+khas,delhi&sensor=false")
headers(r)
```

**Comment by scottmmjackson** [comment]
This looks like it can be closed. If you can reproduce the issue, please let me know.
