### ISSUE TITLE
Error in get("f", environment(CoordMap$train)) : object 'f' not found

### ISSUE THREAD

**Issue by edumucelli** [dkahle/ggmap#144]
By trying to use the `qmplot` I am facing the following error:

`qmplot(Longitude, Latitude, data = geolocalized_crimes, maptype = "toner-lite", geom = "density2d", color = I("red"))`
`Using zoom = 8.`..
`Error in get("f", environment(CoordMap$train)) : object 'f' not found`

Bellow is the session info, which may help to debug.

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggmap_2.7         scales_0.4.1      reshape_0.8.6     plyr_1.8.4       
[5] tidyr_0.6.1       data.table_1.10.0 ggplot2_2.2.1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9       git2r_0.18.0      bitops_1.0-6      tools_3.3.2      
 [5] digest_0.6.12     memoise_1.0.0     tibble_1.2        gtable_0.2.0     
 [9] lattice_0.20-34   png_0.1-7         DBI_0.5-1         mapproj_1.2-4    
[13] curl_2.3          proto_1.0.0       withr_1.0.2       stringr_1.1.0    
[17] dplyr_0.5.0       httr_1.2.1        RgoogleMaps_1.4.1 maps_3.1.1       
[21] devtools_1.12.0   grid_3.3.2        R6_2.2.0          jpeg_0.1-8       
[25] tcltk_3.3.2       sp_1.2-4          reshape2_1.4.2    magrittr_1.5     
[29] assertthat_0.1    geosphere_1.5-5   colorspace_1.3-2  stringi_1.1.2    
[33] lazyeval_0.2.0    munsell_0.4.3     rjson_0.2.15 
```    

What is missing on my setup?

**Comment by happyshows** [comment]
Same error here:
```
> qmplot(lon, lat, data = crime)
Using zoom = 7...
Source : http://tile.stamen.com/toner-lite/7/28/49.png
Source : http://tile.stamen.com/toner-lite/7/29/49.png
Source : http://tile.stamen.com/toner-lite/7/30/49.png
Source : http://tile.stamen.com/toner-lite/7/31/49.png
Source : http://tile.stamen.com/toner-lite/7/28/50.png
Source : http://tile.stamen.com/toner-lite/7/29/50.png
Source : http://tile.stamen.com/toner-lite/7/30/50.png
Source : http://tile.stamen.com/toner-lite/7/31/50.png
Source : http://tile.stamen.com/toner-lite/7/28/51.png
Source : http://tile.stamen.com/toner-lite/7/29/51.png
Source : http://tile.stamen.com/toner-lite/7/30/51.png
Source : http://tile.stamen.com/toner-lite/7/31/51.png
Source : http://tile.stamen.com/toner-lite/7/28/52.png
Source : http://tile.stamen.com/toner-lite/7/29/52.png
Source : http://tile.stamen.com/toner-lite/7/30/52.png
Source : http://tile.stamen.com/toner-lite/7/31/52.png
Source : http://tile.stamen.com/toner-lite/7/28/53.png
Source : http://tile.stamen.com/toner-lite/7/29/53.png
Source : http://tile.stamen.com/toner-lite/7/30/53.png
Source : http://tile.stamen.com/toner-lite/7/31/53.png
Source : http://tile.stamen.com/toner-lite/7/28/54.png
Source : http://tile.stamen.com/toner-lite/7/29/54.png
Source : http://tile.stamen.com/toner-lite/7/30/54.png
Source : http://tile.stamen.com/toner-lite/7/31/54.png
Error in get("f", environment(CoordMap$train)) : object 'f' not found
```

**Comment by adokter** [comment]
I have the same problem. A temporary fix is installing an earlier version of ggplot2:
```
install_github("hadley/ggplot2@v2.2.0")
```
It seems that some of the internal functions of `ggplot2` used by `ggmap` have changed in the transition of `ggplot v2.2.0` to `v2.2.1`, requiring a fix of `ggmap`.

**Comment by ldeassis** [comment]
What is the solution WITHOUT changing ggplot2 installation?

**Comment by brophyj** [comment]
I had the same problem despite all packages being updated from GitHub. Only solution that worked for me was what was proposed by adokter.

**Comment by zoanthal** [comment]
Working with the development version of tidyverse/ggplot, I get the following output/code:

> worldmap<-get_map(location = c(lon = 0, lat = 0), scale=2,zoom=1, maptype = "terrain", source = "google")
Source : https://maps.googleapis.com/maps/api/staticmap?center=0,0&zoom=1&size=640x640&scale=2&maptype=terrain&language=en-EN
> worldmap
1280x1280 terrain map image from Google Maps.  see ?ggmap to plot it.
> p <- ggmap(worldmap)
Error in get("f", environment(CoordMap$train)) : object 'f' not found

Working with the standard CRAN ggplot, I get the coord_pro() error described [here](https://github.com/hrbrmstr/ggalt/issues/33).

**Comment by DrChrisLevy** [comment]
I also have the same issue. 
When I use the most recent dev version of ggplot I get the error.

Error in get("f", environment(CoordMap$train)) : object 'f' not found

When I use a different version off ggplot such as 
devtools::install_github("hadley/ggplot2@v2.2.0")

then ggmap works.

Other packages I use such as plotly require new versions of ggplot so then I am not able to use ggmap. 

Anyone find a solution yet? That is, to use the most recent version of ggplot and get ggmap to work.

**Comment by jmigueldelgado** [comment]
same here. moving back to devtools::install_github("hadley/ggplot2@v2.2.0") does not work for: Error in get(Info[i, 1], envir = env) : lazy-load database '/home/delgado/R/x86_64-pc-linux-gnu-library/3.3/ggplot2/R/ggplot2.rdb' is corrupt

**Comment by lmegna** [comment]
I am having the same problem as jmigueldelgado. Using R 3.3.3, ggplot2 2.2.0 (installed as described above), and ggmap 2.7 (installed from GitHub). Also had the same problem as original poster when using current version of ggplot2.

**Comment by jonathandroth** [comment]
I originally had the same issue as jmigueldelgado and Imegna, but I found that Restart R fixed this.

Nonetheless, it would be great if there could be a workaround that didn't require reverting to earlier versions of ggplot

**Comment by rossgore** [comment]
Had this same problem today. Used the adokter solution and it worked.

**Comment by CrisBMoya** [comment]
I can plot the map using adokter solution but there are now 14 warnings:
```
14: In structure(NULL, class = "waiver") :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```
They are all the same. Don't know if this is affecting the map plotting in some way. I really would like to work without warnings.

**Comment by scottmmjackson** [comment]
This should be fixed, please update the issue if you can reproduce after installing the latest from `devtools::install_github`
