### ISSUE TITLE
not able to install the package

### ISSUE THREAD

**Issue by AshwiniRS** [dkahle/ggmap#147]
install_github("dkahle/ggmap")

Downloading GitHub repo dkahle/ggmap@master
from URL https://api.github.com/repos/dkahle/ggmap/zipball/master
Installing ggmap

Error in if (download_method_secure()) {: missing value where TRUE/FALSE needed
Traceback:

1. install_github("dkahle/ggmap")
2. install_remotes(remotes, quiet = quiet, ...)
3. vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
4. FUN(X[[i]], ...)
5. install(source, ..., quiet = quiet, metadata = metadata)
6. install_deps(pkg, dependencies = initial_deps, upgrade = upgrade_dependencies, 
 .     threads = threads, force_deps = force_deps, quiet = quiet, 
 .     ...)
7. dev_package_deps(pkg, repos = repos, dependencies = dependencies, 
 .     type = type)
8. filter_duplicate_deps(package_deps(deps, repos = repos, type = type), 
 .     installing$remote_deps %||% remote_deps(pkg))
9. rbind(cran_deps, remote_deps)
10. package_deps(deps, repos = repos, type = type)
11. cran_mirror()

Please help me to fix it.

**Comment by bbrewington** [comment]
This seems to be more of a local R instance or `install_github` issue rather than a ggmap issue.

Someone submitted an issue on the github repo for `dplyr` with a similar problem: https://github.com/hadley/dplyr/issues/1433

**Comment by scottmmjackson** [comment]
Seems to be fixed. If this continues to be a problem, please update the issue.
