### ISSUE TITLE
Error in f(...) : could not find function "viewport"

### ISSUE THREAD

**Issue by snowhyzhang** [dkahle/ggmap#148]
hello,

I am trying to add inset of my polygon into a map according to "ggmap: Spatial Visualization with ggplot2" but i got an error.

here is the code:

houston <- get_map("houston", zoom = 14)
HoustonMap <- ggmap(houston, extent = "device", legend = "topleft")

overlay <- stat_density2d(aes(x = lon, y = lat, fill = ..level.., alpha = ..level..), 
                          bins = 4, geom = "polygon", data = violent_crimes)
HoustonMap + overlay + inset(grob = ggplotGrob(ggplot() + overlay + theme_inset()),
                             xmin = -95.35836, xmax = Inf, ymin = -Inf, ymax = 29.75062)

when I use inset function, i get an error: Error in f(...) : could not find function "viewport".

**Comment by scottmmjackson** [comment]
Should be fixed. Let me know if you can reproduce.
