### ISSUE TITLE
Error gglocator() - Viewport 'NA' was not found

### ISSUE THREAD

**Issue by snair1591** [dkahle/ggmap#151]
I've been trying to find specific coordinates in my plot using gglocator() in 'ggmap' package. I keep getting this error: 

> 'Error in grid.Call.graphics(L_downviewport, name$name, strict) :   
> Viewport 'NA' was not found'

here's a reproducible code similar to my problem:   

     require(ggplot2)
        require(ggmap)
        x1 <- seq(1,1000,25)
        x2 <- rnorm(40,mean = 1, sd = 0.25)
        df <- data.frame(x1,x2)
        bardf <- data.frame(x = c(150,500,750), height = c(1.4, 1.4,1.2), width = c(50,70,90))
        p <- ggplot() + geom_bar(data = bardf, aes(x,height, width = width), fill = "white", stat = "identity") +
          geom_line(data = df, aes(x1,x2))
        print(p)
        gglocator()

And this is my sessionInfo():

    [![R version 3.3.2 (2016-10-31)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)
    
    locale:
    \[1\] LC_COLLATE=English_United States.1252 
    \[2\] LC_CTYPE=English_United States.1252   
    \[3\] LC_MONETARY=English_United States.1252
    \[4\] LC_NUMERIC=C                          
    \[5\] LC_TIME=English_United States.1252    
    
    attached base packages:
    \[1\] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    \[1\] ggplot2_2.2.0
    
    loaded via a namespace (and not attached):
     \[1\] labeling_0.3     colorspace_1.3-1 scales_0.4.1     assertthat_0.1  
     \[5\] lazyeval_0.2.0   plyr_1.8.4       tools_3.3.2      gtable_0.2.0    
     \[9\] tibble_1.2       Rcpp_0.12.8      grid_3.3.2       munsell_0.4.3   
    > require(ggmap)
    Loading required package: ggmap
    Google Maps API Terms of Service: http://developers.google.com/maps/terms.
    Please cite ggmap if you use it: see citation('ggmap') for details.
    > sessionInfo()
    R version 3.3.2 (2016-10-31)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)
    
    locale:
    \[1\] LC_COLLATE=English_United States.1252 
    \[2\] LC_CTYPE=English_United States.1252   
    \[3\] LC_MONETARY=English_United States.1252
    \[4\] LC_NUMERIC=C                          
    \[5\] LC_TIME=English_United States.1252    
    
    attached base packages:
    \[1\] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    \[1\] ggmap_2.6.1   ggplot2_2.2.0
    
    loaded via a namespace (and not attached):
     \[1\] Rcpp_0.12.8       magrittr_1.5      maps_3.1.1        munsell_0.4.3    
     \[5\] colorspace_1.3-1  geosphere_1.5-5   lattice_0.20-34   rjson_0.2.15     
     \[9\] jpeg_0.1-8        stringr_1.1.0     plyr_1.8.4        tools_3.3.2      
    \[13\] grid_3.3.2        gtable_0.2.0      png_0.1-7         lazyeval_0.2.0   
    \[17\] assertthat_0.1    tibble_1.2        mapproj_1.2-4     reshape2_1.4.2   
    \[21\] labeling_0.3      sp_1.2-3          stringi_1.1.2     RgoogleMaps_1.4.1
    \[25\] scales_0.4.1      proto_1.0.0][1]][1]

I am trying to calculate the area under the plot and between the barplots. My idea is to find the coordinates (eg: red circle in the plot) of intersection between these plots, use geom_area or geom_ribbon to shade the region and the calculate the area (which I still need to figure out). Any suggestions or better methods to tackle this problem would be much appreciated.

**Comment by mvkorpel** [comment]
I don't have suggestions for you about how to perform the analysis, but the error seems to be gone in the latest development version of `ggmap`. If unsure about how to install it from GitHub, see my comment [here](https://github.com/dkahle/ggmap/issues/127#issuecomment-286697898).

**Comment by snair1591** [comment]
Ok Thanks mvkorpel!
