### ISSUE TITLE
Citation bibtex format

### ISSUE THREAD

**Issue by academikuser** [dkahle/ggmap#152]
I can't just paste [your citation](https://cran.rstudio.com/web/packages/ggmap/citation.html) into bibdesk.  It shouldn't end with the extra comma. And just add a citekey before the first comma. Corrected version:

    @Article{ggmap,
            author = {David Kahle and Hadley Wickham},
            title = {ggmap: Spatial Visualization with ggplot2},
            journal = {The R Journal},
            year = {2013},
            volume = {5},
            number = {1},
            pages = {144--161},
            url = {http://journal.r-project.org/archive/2013-1/kahle-wickham.pdf}}

**Comment by mvkorpel** [comment]
The comma after the last field is not an error. On the contrary, it is [convenient](http://tex.stackexchange.com/q/82313/23160). The comma is created by functions in the `utils` package that handle `citEntry()` or `bibEntry()` data in `inst/CITATION`.

It might be nice to have a default citekey, but I think it should be more complex than just `ggmap` to avoid name clashes. Maybe `kahle-wickham:2013` as in the ["official" R Journal BibTeX entries](https://journal.r-project.org/archive/2013-1/index-bib.html). This could be achieved by adding `key = "kahle-wickham:2013"` as an argument to the `citEntry()` call in `ggmap`'s `inst/CITATION`.
