### ISSUE TITLE
class(crime$time) is c( "POSIXt"  "POSIXct")

### ISSUE THREAD

**Issue by edzer** [dkahle/ggmap#157]
```r
> library(ggmap)
Loading required package: ggplot2
Google Maps API Terms of Service: http://developers.google.com/maps/terms.
Please cite ggmap if you use it: see citation("ggmap") for details.
> data(crime)
> class(crime$time)
[1] "POSIXt"  "POSIXct"
```
this should IMO be:
```r
[1] "POSIXct"  "POSIXt"
```
see e.g. section "Details" in the documentation of `POSIXct`: "A virtual class `POSIXt` exists from which both of the classes inherit: it is used to allow operations such as subtraction to mix the two classes."

**Comment by scottmmjackson** [comment]
Should be fixed. Let me know if it still doesn't work after installing the latest from github.
