### ISSUE TITLE
how to draw a world map in ggmap

### ISSUE THREAD

**Issue by l0o0** [dkahle/ggmap#164]
I have found some ways to draw a world map in R, but the code is really complicate. Is there any way to draw a world map in ggmap?

**Comment by randomgambit** [comment]
interested as well

**Comment by thorellk** [comment]
Also interested :)

**Comment by mvkorpel** [comment]
With the current development version here on GitHub, something like the following should work:

`ggmap(get_stamenmap(bbox = c(left = -180, bottom = -80, right = 179.9999, top = 85), zoom = 3))`

**Comment by JoGall** [comment]
@mvkorpel's answer above worked for me; just make sure you've downloaded the latest version from github, not `install.packages()`!

**Comment by scottmmjackson** [comment]
@mvkorpel saves the day again 😄
