### ISSUE TITLE
Bug (?) when getting google maps that are not square

### ISSUE THREAD

**Issue by jonnybaik** [dkahle/ggmap#17]
It seems that the function get_googlemap does not like it when I request a rectangular map size.

I have R 3.0.0 running on Ubuntu 12.04 and ggmap version 2.3. When I run the following code, the map is not what I expect.

map_center <- c(lon=-123.1119, lat=49.2505)
test <- get_googlemap(center=map_center, zoom=3, maptype="satellite", size=c(640,320))
ggmap(test)

When I change the size parameter to any square dimensions, I get a nice map

**Comment by dannguyen** [comment]
@krlmlr Yep, I'm still getting this error as of ggmap_2.5.2 and ggplot2_1.0.1

### Square 

```R
goog_map <- get_googlemap(size = c(200,200), zoom = 6, scale = 2)    
ggmap(goog_map, extent = 'panel')
```

Resulting URL: http://maps.googleapis.com/maps/api/staticmap?center=29.763284,-95.363271&zoom=6&size=200x200&scale=2&maptype=terrain&sensor=false

![image](https://cloud.githubusercontent.com/assets/121520/9692583/d53c4160-52fe-11e5-972a-e00388eea81e.png)


### 200x100

```R
goog_map <- get_googlemap(size = c(200,150), zoom = 6, scale = 2)    
ggmap(goog_map, extent = 'panel')
```

Result URL:

http://maps.googleapis.com/maps/api/staticmap?center=29.763284,-95.363271&zoom=6&size=200x150&scale=2&maptype=terrain&sensor=false

Result PNG:

![image](https://cloud.githubusercontent.com/assets/121520/9692616/2263d4e4-52ff-11e5-8b99-07b620e73660.png)

What PNG should actually look like:

![image](https://cloud.githubusercontent.com/assets/121520/9692624/32cd5a9e-52ff-11e5-9297-721ad6d52796.png)

**Comment by dkahle** [comment]
Got it, thanks for the bump!
