### ISSUE TITLE
Warning message: `panel.margin` is deprecated. Please use `panel.spacing` property instead 

### ISSUE THREAD

**Issue by openpencil** [dkahle/ggmap#174]
Hi,

Just wanted to report that `ggmap` plots now raise this warning: `Warning message: panel.margin is deprecated. Please use  panel.spacing  property instead` because `panel.margin` is deprecated in ggplot 2.2.0.

**Comment by mvkorpel** [comment]
I think the issue has been solved in the development version, commit b1c002d2c1444acf8b67dee5c51dc7f38ba64ee6.

**Comment by openpencil** [comment]
Thank you for your reply! Any idea when this fix would make it to the production version?

**Comment by mvkorpel** [comment]
I'm just a small-time contributor to the project. That means I don't know, sorry.

**Comment by openpencil** [comment]
Thank you so much for contributing! `ggmap` does rock and I am sure it is due to every single (tiny or otherwise) contributions from the author and the community! 👍  

I look forward to this warning being fixed in the CRAN version, whenever that may be.
