### ISSUE TITLE
get("f", environment(CoordMap$train)) : object 'f' not found

### ISSUE THREAD

**Issue by q623928815** [dkahle/ggmap#176]
ggplot has Renamed coord$train to coord$setup_panel_params on Jan 25
will cause: Error in get("f", environment(CoordMap$train)) : object 'f' not found  ,  when ggmap(map).
please fix it

**Comment by mvkorpel** [comment]
See #144 and #154.

**Comment by scottmmjackson** [comment]
#154 has merged. If you can reproduce this after upgrading to latest github, please let me know.
