### ISSUE TITLE
route() function example from manual doesn't work

### ISSUE THREAD

**Issue by calz1** [dkahle/ggmap#177]
I'm using the latest build from GitHub after not trying it for a few months. My old code for showing a route returned an error so I tried...

```
> from <- "houston, texas" 
> to <- "waco, texas" 
> route_df <- route(from, to, structure = "route") 
Source : https://maps.googleapis.com/maps/api/directions/json?origin=houston%2C%20texas&destination=waco%2C%20texas&mode=driving&units=metric&alternatives=false&key=<my key removed>
Error in rep(LETTERS[k], stepsPerRoute[k]) : invalid 'times' argument

```

**Comment by mvkorpel** [comment]
The example works for me. You could try debugging, for example by issuing the command

```
debugonce(route)
```

followed by the example code. Then, step through the function by repeatedly hitting Enter, until you see the following statement about to be evaluated:

```
stepsPerRoute <- vapply(tree$routes, function(route) length(route$legs[[1]]$steps), numeric(1))
```

So, the variable `tree` (the result of a network query) must have an element called `routes`, and this must be a list with a certain structure. Inspect `tree` by typing the following commands (expected results are commented out):

```
names(tree)
# [1] "geocoded_waypoints" "routes"             "status"            
length(tree$routes)
# [1] 1
names(tree$routes[[1]])
# [1] "bounds"            "copyrights"        "legs"             
# [4] "overview_polyline" "summary"           "warnings"         
# [7] "waypoint_order"   
length(tree$routes[[1]]$legs)
# [1] 1
names(tree$routes[[1]]$legs[[1]])
# [1] "distance"            "duration"            "end_address"        
# [4] "end_location"        "start_address"       "start_location"     
# [7] "steps"               "traffic_speed_entry" "via_waypoint"       
length(tree$routes[[1]]$legs[[1]]$steps)
# [1] 23
```

The final value, 23 in this case, will be used as the `times` argument of the `rep` expression which failed in the example.

Stepping further into the function, we see the following code:

```
nRoutes <- length(stepsPerRoute)
routeLabel <- NULL
for (k in 1:nRoutes) {
    routeLabel <- c(routeLabel, rep(LETTERS[k], stepsPerRoute[k]))
}
```

The code assumes that `nRoutes` is at least `1`. I guess it might be `0` here, and in that case the `for` loop fails to fulfill its apparent goal of going through every route (none!) returned by the network query, as `k` gets the values `1` and `0` when no routes are returned. The result of `numeric(0)[1]` is `NA_real_`, and that is an invalid argument to `rep`.

**Comment by calz1** [comment]
OK, I think I figured it out.

First:
```
library(ggmap)
register_google(key = "<my key removed>")
ggmap_credentials()
options(repr.plot.width=7, repr.plot.height=5)

```
gives:

> Google - 
>    key : <my key removed>
>    account_type : standard 
>    day_limit : 2500 
>    second_limit : 50 
>    client :  
>    signature :  

then:

```
from <- "houston, texas" 
to <- "waco, texas" 
debugonce(route)
route_df <- route(from, to, structure = "route") 
```

 following your instructions I got:
```
debug: stepsPerRoute <- vapply(tree$routes, function(route) length(route$legs[[1]]$steps),
    numeric(1))
Browse[2]> names(tree)
[1] "error_message" "routes"        "status"
Browse[2]> tree$error_message
[1] "This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.d
evelopers.google.com/apis/api/directions_backend?project=_"
```

It appears there was _another_ API I had to enable for directions (versus just getting map images). After I did that, it worked.
