### ISSUE TITLE
Data Science Toolkit down, causing `geocode` with `source = "dsk"` to fail

### ISSUE THREAD

**Issue by alistaire47** [dkahle/ggmap#180]
Without explanation (as far as I can find), [Data Science Toolkit](http://www.datasciencetoolkit.org/) ([source](https://github.com/petewarden/dstk)) has become non-responsive for at least a few days, which causes `geocode` with `source = "dsk"` to hang and eventually return `NA`s and warn, e.g.

```r
> ggmap::geocode('Washington DC', source = 'dsk')
Information from URL : http://www.datasciencetoolkit.org/maps/api/geocode/json?address=Washington%20DC&sensor=false
  lon lat
1  NA  NA
Warning messages:
1: In readLines(connect, warn = FALSE) :
  URL 'http://www.datasciencetoolkit.org/maps/api/geocode/json?address=Washington%20DC&sensor=false': status was 'Couldn't connect to server'
2: In ggmap::geocode("Washington DC", source = "dsk") :
    geocoding failed for "Washington DC".
  if accompanied by 500 Internal Server Error with using dsk, try google.
```
I have no idea if it's coming back, though it _was_ very generous in supplying free services, which may have caused some undoing. If it's possible to confirm that it's gone, the source should be removed. For the mean time, waiting it out is ok, I guess, though maybe users should be alerted.

**Comment by mvkorpel** [comment]
It appears to be working now. The Data Science Toolkit website has the following note:

> **Notice: Recent Outages**
> DSTK has been receiving a large amount of traffic lately, exceeding the limits of our servers. If you are using DSTK for business-critical applications, we strongly advise you  host your own server  so that you are not affected by outages.

**Comment by alistaire47** [comment]
Great! I'm really glad it's not gone. Trying a couple queries, it works, but for unclear reasons is being quite a bit more finicky about the input it will take than it used to be, e.g.

```r
ggmap::geocode('Eiffel Tower, Paris, France', source = 'dsk')
```
used to work, but now returns status 500.

Regardless, it's running at least, so I'll close this issue.

**Comment by rmcarder** [comment]
Appears to be down again? Haven't been able to connect for a few days.

**Comment by annabelrothschild** [comment]
Is it down still? I'm getting the same error message as the original posting.

**Comment by rmcarder** [comment]
Yes, still timing out when I try to set source to dsk for geocoding in R.

**Comment by jonrobinson2** [comment]
This works now?

**Comment by jonrobinson2** [comment]
Code using version 2.6.1 of this package with source='dsk' works on my
machine.

**Comment by dkahle** [comment]
*Hangs head in shame.* I feel like every time I've tried this it just hangs forever. In the most recent version I threw in a hard `stop()`, feeling that it'd been killed; but I just commented out that line and it appears to work properly. I'll remove that line and push. Thanks! (And sorry!)
