### ISSUE TITLE
Error in if (theme$panel.ontop) { : argument is of length zero

### ISSUE THREAD

**Issue by scottmmjackson** [dkahle/ggmap#185]
Repro steps:

```
ggplot2::qplot() + ggmap::theme_nothing()
```

Relevant package versions:

```
$proto
[1] ‘1.0.0’

$RgoogleMaps
[1] ‘1.4.1’

$png
[1] ‘0.1.7’

$plyr
[1] ‘1.8.4’

$reshape2
[1] ‘1.4.2’

$rjson
[1] ‘0.2.15’

$mapproj
[1] ‘1.2.5’

$jpeg
[1] ‘0.1.8’

$geosphere
[1] ‘1.5.7’

$digest
[1] ‘0.6.12’

$scales
[1] ‘0.5.0.9000’

$dplyr
[1] ‘0.7.4’

$bitops
[1] ‘1.0.6’

> packageVersion("ggplot2")
[1] ‘2.2.1.9000’
```

No traceback but the error appears to possibly originate in https://github.com/tidyverse/ggplot2/blob/41f154f5eb89f9939c149645611a5834eb674309/R/layout.R

**Comment by scottmmjackson** [comment]
A little more digging:

`argument is of length zero` tends to come up when an if statement tests a NULL value:

```
> if(NULL) { }
Error in if (NULL) { : argument is of length zero
```

This probably means that the correct way to deal with this is to update the `theme_nothing()` function to set `panel.ontop` in the theme object.

**Comment by robsalasco** [comment]
any update on this?

**Comment by scottmmjackson** [comment]
I'm in contact with the maintainer. Will update when I can.

**Comment by fishkey** [comment]
Any update on this?

**Comment by scottmmjackson** [comment]
See my previous update. `RStudio:::conf` is this week.

**Comment by scottmmjackson** [comment]
This should be fixed.
