### ISSUE TITLE
ggmap doesnt download the map.

### ISSUE THREAD

**Issue by cosmos2006** [dkahle/ggmap#189]
I am using ggmap (developer version: 2.7) behind the proxy and getting error while downloading the map image (png). here is the script:
> library(ggmap)
> india <- get_map(location = 'India', zoom = 5)
error is 
&&&&&&&&&&&&&&&&&&&
Error in download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") : 
  cannot open URL 'https://maps.googleapis.com/maps/api/staticmap?center=India&zoom=5&size=640x640&scale=2&maptype=terrain&language=en-EN'
In addition: Warning message:
In download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") :
  URL 'https://maps.googleapis.com/maps/api/staticmap?center=India&zoom=5&size=640x640&scale=2&maptype=terrain&language=en-EN': status was 'HTTP response code said error'
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

When I used the "curl" methods, i.e.
> options(download.file.method = "curl")
> india <- get_map(location = 'India', zoom = 5)
Error is:
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
curl: (56) Received HTTP code 407 from proxy after CONNECT
Error in download.file(url, destfile = destfile, quiet = !messaging, mode = "wb") : 
  'curl' call had nonzero exit status
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

How to overcome this problem.

Regards
Mradul

**Comment by mvkorpel** [comment]
407 is a [proxy authentication required](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) [error](https://tools.ietf.org/html/rfc7235#section-3.2). There is an [RStudio document](https://support.rstudio.com/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-or-HTTPS-Proxy) about proxy configuration in R, which also points to the official [`download.file()`](http://stat.ethz.ch/R-manual/R-patched/library/utils/html/download.file.html) documentation.

Although no proxy authentication was involved, I was able to get the `"curl"` download method working on my work computer by following a similar procedure.
