### ISSUE TITLE
Inquiring about fraction argument 

### ISSUE THREAD

**Issue by udayguntupalli** [dkahle/ggmap#196]
Hello, 
     I have a question about the function documentation in the library. There is a function called make_bbox which accepts latitude , longitude and a fraction "f". 
     Could you shed some light on what the fraction signifies  ?
     For e.g. If I have a set of coordinates,  as shown below, how can I generate the bounding box within a 5 mile radius using the fraction argument ? 

  `Lat <- 47.80

  Lon <- -122.00

  Rad <- 0.05 

  BBox <- ggmap::make_bbox(lon = Lon,lat = Lat,f = Rad)
`

Best
Uday

**Comment by dkahle** [comment]
Sure. `make_bbox()` essentially just takes in a vector of latitudes and longitudes and creates a reasonable box around them that contains them.  What people typically want when they do that is for the box to extend a little past the observations themselves, so you'll add a padding of, say, 5% on each side.  That's the argument `f`; see `?grDevices::extendrange` for more details.
