### ISSUE TITLE
Error in readJPEG(tmp) :    JPEG decompression error: Not a JPEG file: starts with 0x89 0x50

### ISSUE THREAD

**Issue by adrfantini** [dkahle/ggmap#203]
`get_stamenmap` seems to fail with some map types, because it expects JPEG maps only.

Reprex:

```
bbox <- c(11.31, 41.16, 14.79, 43.986)
get_stamenmap(as.vector(bbox), zoom = 7, maptype="terrain")
```
The output is:
```
Map from URL : http://tile.stamen.com/terrain/7/68/46.jpg
Error in readJPEG(tmp) : 
  JPEG decompression error: Not a JPEG file: starts with 0x89 0x50
```
This is because the correct tile is a png:
http://tile.stamen.com/terrain/7/68/46.png
![46](https://user-images.githubusercontent.com/12826141/37205772-597a3440-2396-11e8-990b-4222f57ecc94.png)

**Comment by mvkorpel** [comment]
The problem has been fixed in the development version of ggmap, available here on GitHub. See #188, #107 and #102.

**Comment by adrfantini** [comment]
Whoops, sorry for that.

Thanks.
