### ISSUE TITLE
Library not loaded: libjpeg.8.dylib

### ISSUE THREAD

**Issue by samhinshaw** [dkahle/ggmap#204]
### Steps to reproduce:

On a mac with `jpeg` install via homebrew, attempt to install ggmap. 

### Result: 
```r
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/3.4/site-library/jpeg/libs/jpeg.so':
  dlopen(/usr/local/lib/R/3.4/site-library/jpeg/libs/jpeg.so, 6): Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/lib/R/3.4/site-library/jpeg/libs/jpeg.so
  Reason: image not found
ERROR: lazy loading failed for package ‘ggmap’
* removing ‘/usr/local/lib/R/3.4/site-library/ggmap’
```

### Problem: 

> The issue is that Homebrew's jpeg formula has been upgraded to v9. 

### Workaround: 

Build libjpeg.8.dylib from source: 

```sh
wget -c http://www.ijg.org/files/jpegsrc.v8d.tar.gz
tar xzf jpegsrc.v8d.tar.gz
cd jpeg-8d
./configure
make
cp ./.libs/libjpeg.8.dylib /usr/local/opt/jpeg/lib
```

### Proposed Solutions

1. Make ggmap compatible with libjpeg 9 (I have no idea how difficult this is), or
2. Prompt user to install libjpeg 8

References: https://stackoverflow.com/questions/32703296/dyld-library-not-loaded-usr-local-lib-libjpeg-8-dylib-homebrew-php

**Comment by mvkorpel** [comment]
The error occurs when loading jpeg (the R package), a dependency of ggmap. Did you try reinstalling jpeg after the upgrade to libjpeg 9?

**Comment by scottmmjackson** [comment]
@samhinshaw Would you mind reopening this issue if @mvkorpel's solution doesn't work?
