### ISSUE TITLE
register_google() before loading ggmap library causes error

### ISSUE THREAD

**Issue by cucumberry** [dkahle/ggmap#205]
Calling `register_google()` without loading the ggmap package causes this error:

```r
ggmap::get_map()
#>  Source : https://maps.googleapis.com/maps/api/staticmap?center=29.763284,-95.363271&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN

ggmap::register_google("XXXXXXXXX")

ggmap::get_map()
#>  Error in if (has_goog_client() && has_goog_signature()) { : 
#>  		missing value where TRUE/FALSE needed
#>  	In addition: Warning messages:
#>  		1: In is.na(goog_client()) :
#>  		is.na() applied to non-(list or vector) of type 'NULL'
#>  	2: In is.na(goog_signature()) :
#>  		is.na() applied to non-(list or vector) of type 'NULL'
```

I'm pretty sure it's because `register_google()` sets `options()$ggmap$google$key`, but not the other options, and then `get_map()` calls `is.na()` on non-existent entries.

**Comment by scottmmjackson** [comment]
@cucumberry I'm going to close this. Would you mind letting us know if this isn't accurate?

**Comment by benscarlson** [comment]
Hello,

I have run into this same problem. I am using ggmap inside a package, and I receive this error whenever I try to use get_map().

I'm managed to find a workaround, and based on what I've found cucumberry is on the right track. It does not appear that the issue has anything to do with having a premium plan. In ggmap, the code seems to assume that google$signature is initialized to NA. However, this value is never initialized, so is.na() returns logical(0), causing the code to fail.

```
centroid <- c(x=12.05171, y=52.06720)
zoom <- 11
maptype <- 'satellite'

ggmap::register_google(key=<api key>)

ggmap::has_goog_key() #true
ggmap::has_goog_signature() #logical(0), so call to get map will fail

ggmap::get_map(location = c(lon = centroid['x'], lat = centroid['y']),
               zoom = zoom, maptype = maptype, scale = 2, messaging=FALSE)

#Error in if (has_goog_client() && has_goog_signature()) { : 
#    missing value where TRUE/FALSE needed
```

I can successfully work around this problem if I explicitly set the value.

```
opt <- getOption('ggmap')
opt$google$signature <- NA
options(ggmap = opt)

ggmap::has_goog_signature() #FALSE
  
ggmap::get_map(location = c(lon = centroid['x'], lat = centroid['y']),
               zoom = zoom, maptype = maptype, scale = 2, messaging=FALSE)

#Result is successfull
#Source : https://maps.googleapis.com/maps/api/staticmap?center=52.0672,12.05171&zoom=11&size=640x640&scale=2&maptype=satellite&language=en-EN&key=<api key>
#1280x1280 satellite map image from Google Maps.  see ?ggmap to plot it.
```

**Comment by dkahle** [comment]
That's right, this is not a Google issue. The problem here is that when you load __ggmap__ it initializes itself with a global option, as you've identified. See [attach.R](https://github.com/dkahle/ggmap/blob/tidyup/R/attach.R). But be careful with this, because 1) this is almost certainly going to change soon to better accommodate the safe handling of API keys and 2) I'm not sure how good of an idea it is to use __ggmap__ without loading it. Hope that helps!

**Comment by benscarlson** [comment]
Hi dkahle,

Thanks a lot for your reply, this is helpful to know. I'm using ggmap inside a package, so my use-case is a little different than the typical one, but I think it is probably still a valid use case. 

Based on what I've read about package best practices, I don't explicitly load the ggmap package. Instead, I put ggmap into the "Imports" section of the DESCRIPTION file. Then, when I call a ggmap function I use the package name as a prefix to any function calls (e.g. ggmap::has_goog_key()). So, maybe this is why ggmap never gets initialized.

Do you have any ideas how I should correctly use ggmap inside a package? Maybe I need to trigger set_ggmap_option() somehow before I call any ggmap function calls?

Thank you!

**Comment by cucumberry** [comment]
I think my problem also came from using ggmap in a package, so not sure what the best practice would be there.

Either way, wouldn't it be a possibility for `register_google()` to set the other options to `NA` if they don't exist yet? Or perhaps for `has_goog_signature()` to return `FALSE` if they don't exist? Or would those not be applicable in light of the coming changes you mentioned? (Or would it be a bad idea for a different reason?)

**Comment by benscarlson** [comment]
I noticed that this issue is officially closed, but there seems to be a lot of discussion about it. Maybe the issue should be re-opened? Or we should create a new, open issue?

**Comment by 12mre1** [comment]
I managed to bypass this by manually attaching the `ggmap` package before the `register_google` function call. I know this is not a great solution, but it did work for me:
`suppressWarnings(library(ggmap))
register_google(key = "ASFC5464F_2333d")
# This is a fake key`
