### ISSUE TITLE
Is there a method to suppress the "Source :  http://tile.stamen.com/terrain/X/XX/XX.png" messaging of `get_map()`?

### ISSUE THREAD

**Issue by DaveRGP** [dkahle/ggmap#208]
When executing a map api call via 
```
get_map(
    location = myLocation,
    maptype = "terrain",
    source = "stamen",
    color = "bw"
)
```
What is the method to prevent the messaging of the function in the style of 
`Source : http://tile.stamen.com/terrain/X/XX/XX.png`?

Messaging TRUE/FALSE does not appear to effect this particular form of messaging, which I believe is created by:

```
# message url
download_error <- inherits(downloaded, "try-error")
  if(download_error) {
    message(paste0("Source FAILED : ", url))
  } else {
    message(paste0("Source : ", url))
  }
```
In [`get_stamenmap.R`](https://github.com/dkahle/ggmap/blob/master/R/get_stamenmap.R), lines 467 - 472.

**Comment by mvkorpel** [comment]
I don't know if this is a bug or an intentional feature. Anyway, it is possible to suppress these messages by using `suppressMessages(get_map(...))`.

**Comment by scottmmjackson** [comment]
Thanks @mvkorpel, I think this can be closed. @DaveRGP if this doesn't solve your problem please let us know.
