### ISSUE TITLE
Incorrect latitude on large area CloudMade maps

### ISSUE THREAD

**Issue by scutum** [dkahle/ggmap#22]
When plotting with source maps from cloudmade the latitude of the grid does not always correspond with the map features. It starts to be noticeable at around zoom level 7 and by level 4 can be off by nearly 3 degrees. 

At zoom levels greater than 8 it seems negligible and longitude seems unaffected. Google and OSM maps do not have this problem.

This example centred on Europe illustrates the problem:

gmap = get_map(location = c(0,50), zoom = 4)
omap = get_map(location = c(0,50), zoom = 4, source="osm")
cmap = get_map(location = c(0,50), zoom = 4, source = 'cloudmade', api_key = api_key)

ggmap(gmap) + geom_hline(yintercept=c(30, 40, 50, 60))
ggmap(omap) + geom_hline(yintercept=c(30, 40, 50, 60))
ggmap(cmap) + geom_hline(yintercept=c(30, 40, 50, 60))

I'll be using the final maps for a commercial project so I cannot use the Google maps. OSM is OK but the advantage of CloudMade is the ability customise with your own style so I can get a nice clean look.

![google-map](https://f.cloud.github.com/assets/5401688/1098287/724a5d6c-171e-11e3-8476-6ec71d8f4d08.png)

![cloudmade-map](https://f.cloud.github.com/assets/5401688/1098289/7e67816a-171e-11e3-8648-446476d432d0.png)

Thanks for reading.

**Comment by dkahle** [comment]
fixed as per another thread.
