### ISSUE TITLE
geocode() fails, problem with SSL CA cert

### ISSUE THREAD

**Issue by damelunx** [dkahle/ggmap#223]
After setting up my new system, some old code using the `geocode()` function no longer works. (I'm using Ubuntu 18.04 and RStudio from the Anaconda package, freshly installed.)
When I run `geocode()`, it gives NA outputs for `lon` and `lat`, and the following warning messages (I erased the location and key):

`Warning messages:
1: In readLines(connect, warn = FALSE) :
  URL 'https://maps.googleapis.com/maps/api/geocode/json?address=#######&key=#######': status was 'Problem with the SSL CA cert (path? access rights?)'
2: In geocode("#######") :   geocoding failed for "#######".
  if accompanied by 500 Internal Server Error with using dsk, try google.`

The CA certificates are up to date, and removing/reinstalling the packages `curl`, `httr`, `openssl` did not help. It seems that the problem lies in the `readLines` function, which indeed in my case only works for normal http websites. I don't know how rare this problem is, but in some places I have seen people describing general problems with readLines and https websites (it used to work on my old system, so I guess it's just bad luck for me now).

Is it possible to replace the readLines commands that `geocode` uses by some other function that can handle https?
TIA!

**Comment by dkahle** [comment]
Hm. Try installing the dev version from the tidyup branch; it uses __httr__ which should play more nicely with the protocols. Have you tried going to the URL it provides in a browser?

**Comment by damelunx** [comment]
Hey thanks for the prompt reply. And indeed, the dev version works! Problem solved. :-)
Thanks again!
