### ISSUE TITLE
ggmap breaks with latest ggplot2 (3.0.0)

### ISSUE THREAD

**Issue by NikNakk** [dkahle/ggmap#228]
ggmap fails with the current CRAN release of ggplot2 (3.0.0). There seem to be multiple issues related to reliance on internal workings of ggplot2 2.2 including:

- The internal structure of `ggplot2::CoordMap` has changed
- Ranges are no longer stored within `plot_info$layout$range`, but in separate `panel_scale_x` and `panel_scale_y` list members

Even though I've worked round both of those (https://github.com/NikNakk/ggmap/tree/fixes-for-ggplot2-3.0.0), I now just get a grey plot.

**Comment by engineeringbigdata** [comment]
Are you still seeing this issue? I'm currently seeing the below errors:

```
ggmap(bw_map_us, extent = "device") + 
        geom_point(data = us_attacks, 
        aes(x = Longitude, y = Latitude, color = Total, size = Total)) + 
        scale_colour_gradient(low = "blue", high = "red")
```

**I receive the below errors:**

Theme element panel.border missing
Theme element axis.line.x.bottom missing
Theme element axis.ticks.x.bottom missing
Theme element axis.line.x.top missing
Theme element axis.ticks.x.top missing
Theme element axis.line.y.left missing
Theme element axis.ticks.y.left missing
Theme element axis.line.y.right missing
Theme element axis.ticks.y.right missing
Error in width_cm(guide$barwidth %||% theme$legend.key.width) :
Unknown input
In addition: Warning messages:
1: panel.margin is deprecated. Please use panel.spacing property instead
2: Removed 1 rows containing missing values (geom_point).

**Comment by dkahle** [comment]
Thanks, just use the dev version for the time being:
```r
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup")
```
