### ISSUE TITLE
get_googlemap() : base_url not secure

### ISSUE THREAD

**Issue by MayuriKetkar** [dkahle/ggmap#229]
## Not getting map by the URL produced by get_googlemap()

The url returned by get_googlemap(), when viewed in browser is showing black screen
If I manually replace 'http' with 'https' the map loads fine.
I debug the function and found the base_url is not secured

Check this url in browser- 
"http://maps.googleapis.com/maps/api/staticmap?center=texas&zoom=10&size=640x640&scale=2&maptype=terrain&sensor=false"

Example:

```r
get_googlemap(center = "texas", zoom = 10, maptype = "terrain", 
    urlonly = TRUE)```

**Comment by dkahle** [comment]
Does this happen in the dev version? I thought it had been fixed?

**Comment by dkahle** [comment]
Great. I'm going to close then, just comment if I need to reopen. Thanks!
