### ISSUE TITLE
ggmap Errors when plotting Longitude and Latitude on Map with ggplot2

### ISSUE THREAD

**Issue by engineeringbigdata** [dkahle/ggmap#230]
About 3 months ago I was creating a few tutorials on mapping with no issues. Today I was starting to create a new tutorial using the same code as before and not I am receiving a vast amount of issues. 

I've seen that this may be a problem with the new version of ggplot2 but there's no definite answer.

Is there a fix for this?

```
install.packages("ggplot2")
install.packages("ggmap")

library(ggplot2)
library(ggmap)

us_attacks <- read.csv("united_states_shark_attacks.csv", stringsAsFactors = FALSE)

bw_map_us <- get_map(location = "United States", zoom = 4, color = "bw")

us_attacks$Latitude <- c(27.766279, 21.094318, 36.116203, 33.856892, 35.630066, 31.054487, 
                         44.572021, 40.298904, 33.040619, 42.165726, 32.806671, 37.769337, 
                         42.230171, 39.318523, 31.169546, 32.741646, 47.400902, 44.693947, 
                         41.597782, 41.680893, 39.063946)
us_attacks$Longitude <- c(-81.686783, -157.498337, -119.681564, -80.945007, -79.806419, 
                          -97.563461, -122.070938, 	-74.521011, -83.643074, -74.948051, 
                          -86.791130, -78.169968, -71.530106, -75.507141, -91.867805, 
                          -89.678696, -121.490494, -69.381927, 	-72.755371, -71.511780, 
                          -76.802101)       
```

Below is the code when I receive the error:
```
ggmap(bw_map_us, extent = "device") + 
        geom_point(data = us_attacks, 
        aes(x = Longitude, y = Latitude, color = Total, size = Total)) + 
        scale_colour_gradient(low = "blue", high = "red")
```

**I receive the below errors:**

Theme element panel.border missing
Theme element axis.line.x.bottom missing
Theme element axis.ticks.x.bottom missing
Theme element axis.line.x.top missing
Theme element axis.ticks.x.top missing
Theme element axis.line.y.left missing
Theme element axis.ticks.y.left missing
Theme element axis.line.y.right missing
Theme element axis.ticks.y.right missing
Error in width_cm(guide$barwidth %||% theme$legend.key.width) :
Unknown input
In addition: Warning messages:
1: panel.margin is deprecated. Please use panel.spacing property instead
2: Removed 1 rows containing missing values (geom_point).

**Comment by dkahle** [comment]
Use the dev version of __ggmap__, not yet on CRAN.
```r
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup")
```
Reboot R, then try again.

**Comment by dkahle** [comment]
Closing, let me know if this doesn't work and I'll reopen.
