### ISSUE TITLE
Allow not displaying the API key

### ISSUE THREAD

**Issue by richierocks** [dkahle/ggmap#232]
DataCamp uses ggmap in several of its courses. We're switching to using our own Google Maps API key, but don't want it displaying every time a student calls `get_map()`. It would be very helpful if you could turn off displaying the API key in a message.

It looks like the full URL is always included in a message in this line

https://github.com/dkahle/ggmap/blob/master/R/get_googlemap.R#L344

It would be great if you could either

1. Not print the API key here, or
1. Turn this message off, via a global option (probably `getOption("verbose")`).

**Comment by RomanAbashin** [comment]
@richierocks There is a workaround with `sink()` that sends all messages to a logfile.

```
# Send all console messages to foo.txt
sink(file("foo.txt", open = "wt"), type = "message")

# Display messages in console again
sink(type="message")
```

**Comment by dkahle** [comment]
@richierocks – Ok, this should be done now, see 4dfe5165 on the tidyup branch. By default, when users load __ggmap__ it comes with a global option (i.e. `getOption("ggmap")`) of `"display_api_key" = FALSE`.  This can be changed with the convenience functions `ggmap_show_api_key()` and `ggmap_hide_api_key()`.  It currently affects `key`, `client`, and `signature` URL keys. Let me know what you think!  If I bugged, I can reopen. :)
