### ISSUE TITLE
Issue with installing install_github("dkahle/ggmap", ref = "tidyup")

### ISSUE THREAD

**Issue by arthurdawndayne** [dkahle/ggmap#236]
Hello Everyone,

Am a newcomer to ggmaps. Just registered and entered my card details for $300 credit. After that, I tried to enter API_Key in get_map and gave:
map <- get_map(location = 'India', source = 'google',zoom = 10, api_key = api_key)
I got this error:
Error in download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=India&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false'
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=India&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false': HTTP status was '403 Forbidden'

Then I looked up in the GitHub and it was suggested that I install devtools and then the code:
install_github("dkahle/ggmap", ref = "tidyup") after which I need to enter the API key using: register_google(key = key)

But when I try to run the code **devtools::install_github("dkahle/ggmap", ref = "tidyup")**  I get this error:

Downloading GitHub repo dkahle/ggmap@tidyup
from URL https://api.github.com/repos/dkahle/ggmap/zipball/tidyup
Installation failed: Failed to connect to api.github.com port 443: Timed out

Kindly let me know what I need to do. I am entirely new to ggmaps.

**Comment by dkahle** [comment]
Hi @arthurdawndayne – you're right about your first issue, you need the newer version. The second issue is a bit more curious, because it appears to be either 1) a bad internet connection, in which case try again, or 2) GitHub refusing to honor the http request. Maybe it doesn't like your IP?

I'm happy continuing the conversation, but I'm going to close the issue as it does not appear to pertain to __ggmap__.

**Comment by arthurdawndayne** [comment]
Thanks the replyy dkahle, indeed it was a connection issue. Worked when I tried from my personal computer.
But now when I try to run **devtools::install_github("dkahle/ggmap", ref = "tidyup")**

I am getting the below error:

**ERROR: dependencies 'rjson', 'digest', 'scales' are not available for package 'ggmap'
* removing 'C:/Users/Ishwarya/Documents/R/win-library/3.4/ggmap'
In R CMD INSTALL
Installation failed: Command failed (1)**

After which get_map() fails with same error

Error in download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=12.9716,77.5946&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false'
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=12.9716,77.5946&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false': HTTP status was '403 Forbidden'

Please let me know how to resolve the issue.

**Comment by dkahle** [comment]
Sure. Your first `**ERROR` is saying that you need to install __rjson__, __digest__, and __scales__.  Try 
```r
install.packages(c("rjson","digest","scales"))
```
and then re-try installing __ggmap__. If you get similar errors, just keep squashing them by installing the packages it needs.  Then check back!
