### ISSUE TITLE
Hospital Service Areas and Hospital Referral Regions Maps

### ISSUE THREAD

**Issue by faerbera** [dkahle/ggmap#240]
Feature request
I work with the Dartmouth Atlas data. We analyze health utilization in the United States based on regions of common health service use - Health Service Areas (HSAs) and Hospital Referral Regions (HRRs). Method notes: http://www.dartmouthatlas.org/downloads/methods/research_methods.pdf

Is there any interest at adding this type of non-geographic area information into GGMap? I'm no developer, but am learning R. It seems the ease of creating maps in GGmap would be a natural fit for this type of special health-data area. 
Thanks!!!
Adrienne Faerber, PhD
Lecturer at The Dartmouth Institute

**Comment by dkahle** [comment]
Hi @faerbera – Thanks for the note; sounds like y'all are doing cool stuff. It's not totally clear to me what exactly you're interested in doing, but it sounds like the application would be better suited for a package that depends on __ggmap__ (or other packages). That way changes to the package could be done independently of __ggmap__.

Thanks for the note!
