### ISSUE TITLE
Same as #191, register_google not found

### ISSUE THREAD

**Issue by scdavis50** [dkahle/ggmap#241]
```r

    library(ggmap)
    register_google(key = "")

```
I'm running R 3.5.1 on Ubuntu 16.04.  I have the development version of ggmap installed.

**Comment by iraklipsyche** [comment]
I'm on a mac and have installed the package but still get this "register_google not found" error.

**Comment by dkahle** [comment]
Sorry, gonna need more to help.  If `register_google()` isn't found, you likely haven't installed the dev version correctly.  Please see the main page for instructions.  Let me know if that doesn't work, I'll re-open.
