### ISSUE TITLE
Help with register_google

### ISSUE THREAD

**Issue by andeaaro** [dkahle/ggmap#249]
Hi, I'm trying to get ggmap to work, and no matter what I do I cannot get the register_google function to work.
I am currently trying to do the following below, but "register_google" doesn't then pop up as an option.
Am I missing something simple? Thanks so much!

install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup")
library("ggmap")
register_google(key = "my-key-here")

**Comment by andeaaro** [comment]
Never mind - I tried it again tonight, and it worked this time!

**Comment by MrMacc** [comment]
I ran into the same issue. I am using macOS el-capitan. 

Below is the steps i've taken to resolve: 
- confirm you've removed the CRAN version of ("ggmap") '2.6.1'. via remove.packages("ggmap")
- once removed you will also need to confirm the removal of ("tibble") using the above method. 
- devtools::install_github("dkahle/ggmap", ref = "tidyup")
- you will be prompted to install tibble, select 'Y'
- Install should begin
- if asked "Do you want to install from sources the package which needs compilation?" select no

**Comment by dkahle** [comment]
Glad to hear it's working. Thanks @MrMacc for the walk through!
