### ISSUE TITLE
R updated = could not find function "register_google"

### ISSUE THREAD

**Issue by ctlamb** [dkahle/ggmap#251]
I updated R to `R version 3.5.1 (2018-07-02) -- "Feather Spray"`

Now  register_google() function appears to be missing.

```r
** testing if installed package can be loaded
* DONE (ggmap)
> library(ggmap)
> register_google("XXX")
Error in register_google("XXX") : 
  could not find function "register_google"
```

**Comment by dkahle** [comment]
Hi @ctlamb – You need to re-install the dev version of __ggmap__, see the main GitHub page. I'm going to try to delete this issue since it contained your API key, but just re-raise the issue if you run into the problem again.
