### ISSUE TITLE
ggmap, Annaconda Jupyter 

### ISSUE THREAD

**Issue by garrettburt** [dkahle/ggmap#254]
I am attempting to use ggmap in an R Jupyter Notebook. I have attempted to install the updated package from github with the following code: 

```r
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup")
ggmap(get_googlemap())
register_google(key = "mykey")
```
I have also attempted to install the package via conda to no avail. When installing via conda skeleton I get an Error: no tags found. 

Not sure if release tags are needed? Possibly similar to this issue (https://github.com/reptalex/phylofactor/issues/11)?

Thanks for the help

**Comment by dkahle** [comment]
After you install, did you load it with `library()`? Not sure what the conda problem is.

**Comment by garrettburt** [comment]
Ya I tried to load it with library(). I'm not sure what the issue is 100%, but it'll be fine. Thanks!
