### ISSUE TITLE
Install failure - install_github("dkahle/ggmap", ref = "tidyup")

### ISSUE THREAD

**Issue by CTO22** [dkahle/ggmap#255]
Yesterday, as I was rushing out of the office I encountered a similar error to [https://github.com/dkahle/ggmap/issues/236] where installation failed due to 'missing' dependencies., 'digest' among them but others as well.  I didn't have time to trouble shoot so I postponed until today and now have a different error.  Now I get the error below:

> if(!requireNamespace("devtools")) install.packages("devtools")
Loading required namespace: devtools
> library(ggmap)
Error in library(ggmap) : there is no package called ‘ggmap’
> devtools::install_github("dkahle/ggmap", ref = "tidyup")
Downloading GitHub repo dkahle/ggmap@tidyup
C:\ArcGIS\gbin\tar.exe: Cannot use compressed or remote archives
C:\ArcGIS\gbin\tar.exe: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
C:\ArcGIS\gbin\tar.exe: Cannot use compressed or remote archives
C:\ArcGIS\gbin\tar.exe: Error is not recoverable: exiting now
External tar failed with `--force-local`, trying without
Error: Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: running command 'tar.exe -zxf "C:\Users\coverton\AppData\Local\Temp\2\RtmpAlu7Jq\file1fec284e6984.tar.gz" -C "C:/Users/coverton/AppData/Local/Temp/2/RtmpAlu7Jq/remotes1fec5f556edd"' had status 2 
2: In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\coverton\AppData\Local\Temp\2\RtmpAlu7Jq\file1fec284e6984.tar.gz" -C "C:/Users/coverton/AppData/Local/Temp/2/RtmpAlu7Jq/remotes1fec5f556edd"’ returned error code 2
3: running command 'tar.exe -ztf "C:\Users\coverton\AppData\Local\Temp\2\RtmpAlu7Jq\file1fec284e6984.tar.gz"' had status 2 
>

**Comment by acmoraes** [comment]
This is what I get trying to install it from the GitHub repo today:

`devtools::install_github("dkahle/ggmap", ref = "tidyup")
Downloading GitHub repo dkahle/ggmap@tidyup
tar.exe: Archive entry has empty or unreadable filename ... skipping.
[...]
tar.exe: Archive entry has empty or unreadable filename ... skipping.
tar.exe: Error exit delayed from previous errors.
Error: Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: running command 'tar.exe -zxf "C:\Users\morae\AppData\Local\Temp\RtmpSmqpZH\filee6c635fec7.tar.gz" -C "C:/Users/morae/AppData/Local/Temp/RtmpSmqpZH/remotese6c7682cfc"' had status 1 
2: In utils::untar(tarfile, ...) :
  ‘tar.exe -zxf "C:\Users\morae\AppData\Local\Temp\RtmpSmqpZH\filee6c635fec7.tar.gz" -C "C:/Users/morae/AppData/Local/Temp/RtmpSmqpZH/remotese6c7682cfc"’ returned error code 1
3: running command 'tar.exe -ztf "C:\Users\morae\AppData\Local\Temp\RtmpSmqpZH\filee6c635fec7.tar.gz"' had status 1`

**Comment by dkahle** [comment]
Hm. Have you installed [Rtools](https://cran.r-project.org/bin/windows/Rtools/)?

**Comment by acmoraes** [comment]
Found the solution online, a bit later. Ran this command:
`Sys.setenv(TAR = "internal")`
As I understand it, it had to do with changing the environment where R was to search for the TAR application. Thank you, anyway!

**Comment by dkahle** [comment]
Great, glad to hear you're back up and running!
