### ISSUE TITLE
optional parameter 

### ISSUE THREAD

**Issue by andzandz11** [dkahle/ggmap#260]
https://developers.google.com/maps/documentation/geocoding/intro

I want to specify the language parameter, but because geocode() has URLencode() internally my & gets scrambled up. Can you just add the options="" param to geocode() that get's appended to the geocode request URL without formatting?

**Comment by dkahle** [comment]
Isn't that what the `inject` argument does? Are there other circumstances where `URLencode()` munges things improperly?

**Comment by andzandz11** [comment]
Thank you for your quick reply.
Unfortunately if I try to chain components the | pipe operator gets scrambled.

```
geocode("Berlin", inject="components=country:GB|country:AU", output="more")
Source : https://maps.googleapis.com/maps/api/geocode/json?address=Berlin&key=xxx&components=country:GB%7Ccountry:AU
       lon      lat                        type     loctype                      address    north    south     east
1 7.308953 50.11835 administrative_area_level_1 approximate rheinland-pfalz, deutschland 50.94231 48.96677 8.508313
     west administrative_area_level_1     country
1 6.11234             Rheinland-Pfalz Deutschland


```
but:
```
> geocode("Berlin", inject="components=country:GB", output="more")
Source : https://maps.googleapis.com/maps/api/geocode/json?address=Berlin&key=xxx&components=country:GB
  lon lat
1  NA  NA

```

works

**Comment by dkahle** [comment]
Hi @andzandz11 – I just tested your two examples; the first works, the second doesn't. (I've been working on this a lot lately.) Is that the behavior you're looking for?

**Comment by andzandz11** [comment]
That is weird.
I took this example directly from the google page for things that should fail.

> If the request contains multiple component filters, the API evaluates them as an AND, not an OR. For example, if the request includes multiple countries components=country:GB|country:AU, the API looks for locations where country=GB AND country=AU, and returns ZERO_RESULTS
https://developers.google.com/maps/documentation/geocoding/intro

But if I enter this in the browser directly by hand it returns 2 results instead of zero. The geocoding API looks first in GB and afterwards in AU. Which is contradicting what is written in google's own readme.

`https://maps.googleapis.com/maps/api/geocode/json?address=high+st+hasting&components=country:AU|country:GB&key=XXX`

Sorry I thought there might be a problem in the package, but it seems the problem is somewhere else.

But anyway this returns 3 results:
`https://maps.googleapis.com/maps/api/geocode/json?address=Berlin&key=XXX&components=country:GB|country:AU`
Sould not return a match in Germany, but the Google Geocoding API still does so.

And this returns zero results.
`https://maps.googleapis.com/maps/api/geocode/json?address=Berlin&key=XXX&components=country:GB`

I wonder what is going on. Seems to be a bug in thier logic evaluation.

**Comment by dkahle** [comment]
Thanks for looking into this. I have problems with the documentation sometime as well - there are many, many pages, and, worse, many of them are very similar. It is difficult to tell when some information is dated. I feel your pain!

I'm going to close this for now, but feel free to follow up if you learn more or with other bugs/feature requests. Thanks!

**Comment by andzandz11** [comment]
Google says:

```
 wa...@google.com <wa...@google.com> #2 Jan 24, 2019 01:06AM
Status: Won't Fix (Intended Behavior)
Thanks for reporting!

After reading the github link, I have to say that this is working as intended.

The reason being that if the request with component filtering has partial matches in the results, it will contain a "partial_match" field that is set to true.
If it doesn't, then it would be an exact match.

Sample
Exact match (without "partial_match") :
https://maps.googleapis.com/maps/api/geocode/json?address=high+st+hasting&components=country:GB&key=YOUR_KEY

Partial Match (with "partial_match") :
https://maps.googleapis.com/maps/api/geocode/json?address=high+st+hasting&components=country:AU|country:GB&key=YOUR_KEY

```
