### ISSUE TITLE
Google API Key - How to Add It?

### ISSUE THREAD

**Issue by murphystout** [dkahle/ggmap#261]
Questions:

1. Does the CRAN version of ggmap support Google API Keys?  (I'm assuming no, see example below).

2. If not, and the github version does, is there a way to install the github version without using devtools/rtools?  It is currently not working with R 3.5.x, and workarounds have not worked for m.

Here's an example, I am using the CRAN version of ggmap.
Using the examples from the ggmap help file, I get 403 forbidden error, presumably because it is not using an API Key:

`hdf <- get_map("houston, texas")`

Error in download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") : 
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=houston,+texas&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false'
In addition: Warning message:
In download.file(url, destfile = tmp, quiet = !messaging, mode = "wb") :
  cannot open URL 'http://maps.googleapis.com/maps/api/staticmap?center=houston,+texas&zoom=10&size=640x640&scale=2&maptype=terrain&language=en-EN&sensor=false': HTTP status was '403 Forbidden'

**Comment by tomasleon** [comment]
@dkahle answers 1) on this package's page in detail: https://github.com/dkahle/ggmap

For 2), devtools is certainly the easiest approach, but you could also clone the repo from github and then build it yourself in R. See: http://kbroman.org/pkg_primer/pages/build.html

**Comment by dkahle** [comment]
Hi @murphystout – Correct, the CRAN version is broken. I am working with CRAN currently on a release, so stay tuned. In the interim, try re-installing the dev version with `devtools::install_github("dkahle/ggmap")`. Restart R, reload __ggmap__, register your API key with `register_google()`, and you should be good to go. Try something like `geocode("waco texas")`, you should know if it is successful.

Let me know how it goes!
