### ISSUE TITLE
get_map not working with Google when using bounding box

### ISSUE THREAD

**Issue by julovi** [dkahle/ggmap#267]
Hi,

I upgraded to version 3.0.0 last week and I noticed that after the upgrade, using get_map with a bounding box and Google maps is not working anymore. Is there any way to put back this functionality? or is there an alternative method to achieve the same result?

## Reproducible Example
```r
reprex::reprex({
    library(ggmap)
   ggmap(get_map(c(left = -97.1268, bottom = 31.536245, right = -97.099334, top = 31.559652), maptype="roadmap", source = "google"))
}, si = TRUE)
```
Thanks!

**Comment by dkahle** [comment]
Got it, thanks!

**Comment by julovi** [comment]
Thanks David, 
are you planning to make a new release soon? the CRAN repository still has 3.0.0 and when I try 
devtools::install_github("dkahle/ggmap")

I get this error:

Installation failed: lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/ggmap/R/ggmap.rdb' is corrupt

**Comment by dkahle** [comment]
Hi @julovi – __ggmap__ was actually just updated last week, so let's try to debug the GitHub install.  Have you tried `devtools::install_github("dkahle/ggmap", force = TRUE")`? Or maybe, `remove.packages("ggmap")` and then reinstall from CRAN?

**Comment by julovi** [comment]
Hi David,

It’s working now, I relaunched R and installed the GitHub version as you suggested (without the trailing double quotation mark) and it worked. The problem was that I tried to installed with loaded libraries (GADMTools, specifically) and that made it crash.

I’m sorry for the noise and thank you for your help!

Cheers,


Julian Villegas, Ph.D.

**Comment by dkahle** [comment]
Great, glad you're back at it!
