### ISSUE TITLE
How to use ggmap within a package

### ISSUE THREAD

**Issue by benscarlson** [dkahle/ggmap#270]
I'm using ggmap inside a package that I'm developing. I'm following recommended practices in the R Packages book: http://r-pkgs.had.co.nz/description.html, which specifies that packages should be loaded via the Imports statement, but not attached. The issue is that ggmap uses .onAttach() to initialize itself but, per the recommended method, the package is never initialized. This results in errors when ggmap does not find settings it expects to fine.

I'm not sure what the right approach should be. Is there a mechanism to call .onAttach() within my package without actually attaching the package? Maybe I need to ignore best practices and just attach the package? Or, maybe ggmap initialization should go in .onLoad()? I'd appreciate any clarification!

**Comment by dkahle** [comment]
Hi @benscarlson! I think this is #264; your characterization of the problem is spot-on. Have you tried doing it with the current dev version on GitHub? Do you still have problems?
