### ISSUE TITLE
value of messaging is ignored with get_stamenmap

### ISSUE THREAD

**Issue by ikosmidis** [dkahle/ggmap#274]
```r
reprex::reprex({
    library(ggmap)
   map <- get_stamenmap(c(left = -97.12, bottom = 31.53, right = -97.09, top = 31.50), maptype = "toner", zoom = 15, messaging = FALSE)
}, si = TRUE)
```

That seems to be from ggmap:::get_stamenmap_tile where `message` statements are floating in the function without a condition.

**Comment by dkahle** [comment]
Thanks for the note. Stamen doesn't appear to require me to push the URL out to the user, so I'll change `messaging` to affect that URL. I am also including [an attribution note](http://maps.stamen.com/#terrain/12/37.7706/-122.3782) from their webpage for every call to `get_stamenmap()`.
