### ISSUE TITLE
Mapdist reports error inside shiny

### ISSUE THREAD

**Issue by jafeerh** [dkahle/ggmap#275]
I was trying mapdist inside shiny. Hen I have more than one 'from' or 'to' it throws error saying that 
_Matching was not perfect, returning all.
Warning: Error in [[: no such index at level 1_

If there is only one 'from' and one 'to' it works perfectly fine though.

Example below

library(shiny)
#> Warning: package 'shiny' was built under R version 3.5.2
library(shinydashboard)
#> Warning: package 'shinydashboard' was built under R version 3.5.2
#> 
#> Attaching package: 'shinydashboard'
#> The following object is masked from 'package:graphics':
#> 
#>     box

ui <- dashboardPage(
  skin = 'black',
  dashboardHeader(title = "Shiny Dashboard template", titleWidth = 370),
  dashboardSidebar(fileInput('readFile', 'Choose csv file'),
                   width = 300),
  
 
  dashboardBody()
) #dashboardPage ends

server <- function(input, output, session) {
  observeEvent(input$readFile, {
  
    #filename <- input$readFile
    
    #zip <- read.csv(filename$datapath)
    
    library(ggmap)
    

    library(digest)
    library(tidyverse)
    
    
    
   
    dist=mapdist("38671",c("13088","13089"))
    print(dist)
    
    
  })
  
}

shinyApp(ui = ui, server = server)  #calling shiny app

**Comment by dkahle** [comment]
I don't get an error when I run that. Can you check again, please?

**Comment by jafeerh** [comment]
Hi

Just checked again. It works fine now. Thanks.

Apologies.

**Comment by dkahle** [comment]
No problem. Thanks!

BTW, for `mapdist()`, use the dev version. There was a bug for which the fix is not yet on CRAN.

**Comment by jafeerh** [comment]
Sure
