### ISSUE TITLE
Google API key

### ISSUE THREAD

**Issue by djhurio** [dkahle/ggmap#29]
It is possible to specify an api key for cloudmade maps with the parameter ```api_key``` for the function ```get_cloudmademap```.

I would like to have the same functionality also for the function ```get_googlemap```. Please add the argument ```api_key``` also for the function ```get_googlemap```. I believe the function ```get_map``` should be adjusted accordingly.

**Comment by py** [comment]
Triple stamped! Google for Business accounts, which grant one the  `clientid` and `signature` used in this package, are quite pricey (>$10k). An alternative is to use a Google Developer API[1], which is free for low usage and pay as you go afterwards. Given users of this fine ggmap package will fall into both categories, I suggest the following. I'll use `geocode()` as an example:

* Break the `source` argument into three options: 
    * `googlebiz`: For business accounts. Requires arguments `client` and `signature`
    * `googledev`: For the Developer API. Requires a new `apikey` argument
    * `dsk`: Data Science Toolkit. I think this site is down; it has timed out all week.
* For the `googledev` option, piece the URL together as follows:
```
https://maps.googleapis.com/maps/api/geocode/json?address=ADDRESS&key=MYKEY
```

1: https://console.developers.google.com

**Comment by amormachine** [comment]
I second this request, which also appears to be duplicated in #92.  In the interim, there appears to be a viable workaround described on StackOverflow:

[Workaround](http://stackoverflow.com/questions/34402979/increase-the-api-limit-in-ggmaps-geocode-function-in-r)

**Comment by SymbolixAU** [comment]
I've written the package [googleway](https://github.com/SymbolixAU/googleway) to access Google Maps API using an API Key. Maybe this is of help?

**Comment by dkahle** [comment]
Got it, thanks!
