### ISSUE TITLE
incorrect latitude alignment of stamen maps

### ISSUE THREAD

**Issue by amyszczepanski** [dkahle/ggmap#32]
When I use source="stamen" with a zoom=5 (or other zooms at the regional / state / country / continent level), the latitude of the map is not aligned with reality.

I have included an example below. You will see by comparing liberty.map1 and liberty.map2 that the zoom=5 map puts the Statue of Liberty in the Catskill region (significantly north of reality). Comparing liberty.map2 and liberty.map3, you will see that the tick-mark for latitude 35 is at the southern border of Tennessee in the Google map and much further north in Tennessee in the stamen map.

I am using R 3.1.0, ggplot2 1.0.0, and ggmap 2.3.

library(ggmap)
library(ggplot2)
#geocode("statue of liberty")

liberty.map1 <- get_map(location = c(lon=-74.0445, lat= 40.68925), source="stamen", maptype="toner", zoom=15)
liberty.map2 <- get_map(location = c(lon=-74.0445, lat= 40.68925), source="stamen", maptype="toner", zoom=5)
liberty.map3 <- get_map(location = c(lon=-74.0445, lat= 40.68925), zoom=5)

ggmap(liberty.map1) + geom_point(x= -74.0445, y= 40.68925, color="red")
ggmap(liberty.map2) + geom_point(x= -74.0445, y= 40.68925, color="red")
ggmap(liberty.map3)

**Comment by dkahle** [comment]
fixed, thanks! (oh, insidious projection problems...)  fortunately this problem only applied to northern (or southern) latitudes for low zoom values, like your situation.
