### ISSUE TITLE
Publish 3.0.1 to CRAN

### ISSUE THREAD

**Issue by ramblingenzyme** [dkahle/ggmap#332]
Back in 2020, 3.0.1 was scoped out in NEWS.md https://github.com/dkahle/ggmap/blob/master/NEWS.md

This is after merging https://github.com/dkahle/ggmap/issues/317 to remove the unused rjson dependency.

Because this version hasn't been published to CRAN and `rjson` doesn't support R 3.6 anymore, installing `ggmap` into a R 3.6 environment fails.

**Comment by dkahle** [comment]
On its way to CRAN now; this should be resolved imminently.

**Comment by ramblingenzyme** [comment]
Thanks @dkahle, much appreciated.
