### ISSUE TITLE
Currently Having Same Problem and Cannot Seem to Get it Figured Out

### ISSUE THREAD

**Issue by DataAnalysisIntern** [dkahle/ggmap#333]
My Code is 
New_List_GGMAP <- geocode(location = New_List_Wiht_Dates_2_DF$New_list_Wiht_Dates_2.Address,
                          output = "all", source = "google")

The Error Put out is:
Error in if (location == "") return(return_failed_geocode(output)) : 
  missing value where TRUE/FALSE needed
I am not sure what the exact problem is and I've tried almost everything in this thread

**Comment by scottmmjackson** [comment]
This looks like a normal missing value error, there is probably an issue with the parameters in your function call.

If you keep having problems, please attach a reprex to this issue.
