### ISSUE TITLE
Wrong maptype string for filetype check of Stamen Watercolor tiles served by Stadia Maps

### ISSUE THREAD

**Issue by pushing-boulders** [dkahle/ggmap#356]
Hello.  I found a small issue with the recent update for the Stamen styles now being served by Stadia Maps.

If you want to use the Watercolor style, the new maptype name is `stamen_watercolor`:

```r
map <- get_stadiamap(bbox, zoom = 12, maptype = "stamen_watercolor", scale = 3)
```

However, currently, this results in the following error:

```r
a > Error in eval(parse(text = text, keep.source = FALSE), envir) : 
   object 'filetype' not found
```

This is a result of the original `maptype`, `watercolor`, still being used to determine if the tiles are jpg or png on [line 306 of get_stadiamap.R](https://github.com/dkahle/ggmap/blob/4cdb1fb9b1c2c800f87acbc63dbc5896347f27be/R/get_stadiamap.R#L306C3-L306C76)

```r
if(maptype %in% c("watercolor")) filetype <- "jpg" else filetype <- "png"
```

It's a simple fix, just update the check from `watercolor` to `stamen_watercolor` and you're all set.  I tested this with a local edit to the library.  I also have a pull request waiting in my fork if that would be helpful.

Thank you for your attention to this.

Take care.

Zachary

**Comment by bjkramerumnedu** [comment]
I am also having a similar problem, when I use the following command:

LGL <- get_stadiamap(bbox=c(left = -92.5, bottom = 41, right = -76, top = 49), zoom = 6, scale=2, maptype = "stamen_toner_background") 

And get the following error: ℹ © Stadia Maps © Stamen Design © OpenMapTiles © OpenStreetMap contributors.
Error in eval(parse(text = text, keep.source = FALSE), envir) : 
  object 'filetype' not found

If this could be fixed, or if I could be pointed in the right direction to resolve this, I'd greatly appreciate it. Thank you :)

**Comment by pushing-boulders** [comment]
Good day, @bjkramerumnedu.

What version of ggmap are you using?  I just tried in mine (4.0.0) and the stamen_toner_background style is working without error:

![image](https://github.com/dkahle/ggmap/assets/106434615/d8a28a7e-c90c-42db-997f-aa8ee6043bda)

Did you also pass your API key?

**Comment by bjkramerumnedu** [comment]
My apologies, I didn't realize the API key was a key that you use to access Stadia maps.

I created a new account and you're right: it works perfectly. Thank you :)

**Comment by pushing-boulders** [comment]
Awesome to hear, @bjkramerumnedu.  No problem.  Glad we figured out this issue.  Different from the Watercolor one, but an issue nonetheless.

All the best!
