### ISSUE TITLE
several style arguments to get_googlemap

### ISSUE THREAD

**Issue by antongrau** [dkahle/ggmap#47]
Is it possible to give more than one style argument to get_googlemap?

I wrote a possible solution, but I am not good with github yet so you get it here:

In line [188](https://github.com/dkahle/ggmap/blob/master/R/get_googlemap.R#L188)
You could insert:
```
if(is.list(style)){
  style <- lapply(style, FUN = function(style) paste(paste(names(style), style, sep = ":"), collapse = "|" ))
}
```
And in line [294](https://github.com/dkahle/ggmap/blob/master/R/get_googlemap.R#L294)
You could add a collapse argument to paste:
```
style_url <- if(!missing(style)){ paste("style=", style, sep="", collapse ="&") } else { "" }
```

This might add support for style arguments in this form:
```
style       <- list()
style[[1]] <- c(feature = "all", element = "labels", visibility = "off")
style[[2]] <- c(feature = "landscape.man_made", element = "geometry", lightness = -100)
geo_map_cph            <- get_googlemap2("Vanløse", zoom = 11, color = "bw", maptype = "terrain", style = style)
map.cph                <- ggmap(geo_map_cph, extent = "device")
map.cph
```

I think you need to adjust the checks for argument validity for this code to work.

**Comment by dkahle** [comment]
I think I can just get it with
```
if(is.list(style)) style <- unlist(style)
```
at line 188, right? (Several style arguments were available before with a named character vector.)
