### ISSUE TITLE
geocode results caching

### ISSUE THREAD

**Issue by JakeRuss** [dkahle/ggmap#48]
Let me see if I can start a conversation about a recent issue.

In the course of batch processing many addresses (1000s...) to geocode, I sometimes hit an error that causes geocode to fail and take with it all of the previously successful executions. It might be an Error 500 (internal server) or something like #24.

I'm wondering what would be the better approach to error handling: in the event of an error should geocode handle this internally and return only the successful results with a warning for the error(s)? Or, should I handle this externally by looping through the list of addresses and submit an address to geocode one by one and cache the successful results separately as part of the loop?

For now the latter is easy enough to do and keep my project moving, but if someone will suggest an approach for geocode to handle this internally, I would have interest to write a patch and submit a pull request.

**Comment by dkahle** [comment]
i agree - that's a big frustration.  caching those seems to make sense, it can be done in essentially the same way as the tiles i think.  if you want to script it and submit a pull request i'm happy to merge it in, otherwise i'll get to it as soon as i can.

**Comment by JakeRuss** [comment]
Thank you David. I will post a note here if I start an attempt to write a patch for it. I just want to make a quick comment now so I can remember this later, that the tiles caching you're referring to can be found in the script, file_drawer.R

**Comment by JakeRuss** [comment]
This feature has been added. Many thanks!

**Comment by tyokota** [comment]
Sorry to resurrect a closed issue but where is the cached object located? I just hit my limit because I tried running my script too many times with various errors.

**Comment by JakeRuss** [comment]
There is a hidden list object called `.GeocodedInformation` where the cached results are stored.

**Comment by tyokota** [comment]
Thank you, JakeRuss! You area lifesaver.
