### ISSUE TITLE
Unwanted spaces while specifying size, scale and style (maybe for other parameters as well)

### ISSUE THREAD

**Issue by virtualmic** [dkahle/ggmap#49]
Hi. Thanks for this very helpful package.

I found that unwanted single space is appearing in the parameters in URL to be sent to Google Maps. When I checked in the code, I saw the following:

```R
  scale_url <- if (!missing(scale)) {
    paste("scale=", scale)
  }
````
In the `paste` function above, `sep=""` is missing and hence an unwanted space is appearing in the generated URL. The same happens for scale, style and maybe other places where I haven't checked.

**Comment by dkahle** [comment]
Previously fixed but not closed, thanks!
