### ISSUE TITLE
Create geom_map() which draws a map layer

### ISSUE THREAD

**Issue by jiho** [dkahle/ggmap#5]
The goal is to allow constructions such as

```
ggplot(data=mydata) +
    geom_map(source="stamen", maptype="toner) +
    geom_point(aes(x=lon, y=lat))
```

`geom_map()` would figure out the bounding box of the data argument (inherited from the ggplot call in the example above) and draw the appropriate map. I should probably also set coord_map even though that kind of breaks the grammar of graphics convention.

**Comment by briatte** [comment]
I know this is an old issue, but would it make sense to have something like

```
geom_map_google
geom_map_osm
geom_map_stamen
geom_map_cloudmade
```

functions to add a layer directly to a `ggplot2` object?

Related: #58

**Comment by scottmmjackson** [comment]
#58 seems like the proper issue to track this. Closing.
