### ISSUE TITLE
The 'toner-lines' map gets its colors inverted

### ISSUE THREAD

**Issue by dannguyen** [dkahle/ggmap#50]
```R
library(ggmap)

mapzoom=13
map_type="toner-lines"
map_source='stamen'

manhattan = c(left = -74.028, bottom = 40.695367, right = -73.92, top = 40.794)
map <-get_stamenmap(
  bbox=manhattan,
  zoom=mapzoom,
  maptype=map_type
)
ggmap(map)
```

This is what an individual tile looks like: 

![img](http://tile.stamen.com/toner-lines/13/2411/3080.png)

This is the result:

![image](https://cloud.githubusercontent.com/assets/121520/6141508/9ad70950-b15b-11e4-8886-979e88730c53.png)

**Comment by dannguyen** [comment]
Oops, it looks like this happens because toner-lines are transparent PNGs, so it has nothing to do with the ggmap call. That said, is there a way to specify the fill behind the map layer? I imagine this is an edge case...

**Comment by dkahle** [comment]
that's right - it was the transparency in the PNGs.  fixed now, thanks!
