### ISSUE TITLE
Importing a stamenmap of Chicago returns a map of Houston

### ISSUE THREAD

**Issue by cguwilliams** [dkahle/ggmap#55]
Entered this command to import a map of __Chicago, IL__: 

`chicagoMap <- get_stamenmap(location = 'Chicago', zoom = 12)`

Was surprised to receive a map of __Houston__, TX instead.

I was able to get a map of Chicago with this command: 

`get_stamenmap(bbox = c(left = -87.9401009, bottom = 41.643919, right = -87.523984, top = 42.0230219), zoom=12)`

But just thought it would be helpful to report this.

**Comment by dkahle** [comment]
`location` is not a valid argument for `get_stamenmap()` (it wants a bounding box instead), but that may not be clear to all users.  I just added a warning in this event. Thanks!
