### ISSUE TITLE
High Zoom Accuracy Issue

### ISSUE THREAD

**Issue by kheric** [dkahle/ggmap#56]
I'm currently building maps at zoom levels around 15-16, sometimes more.  The stamen maps ("toner" type) seems to be more accurate than the other types.  All of my coordinates are currently shifted a little to the left along the longitude from where they should be (they are locations for buildings only they're found in streets and parks).  

For example (inaccurate):
ny_plot<-ggmap(get_map(location=center,zoom=16,maptype='terrain'))
ny_plot + geom_point(x= -73.96457, y= 40.80993, color="red")

versus (accurate):
ny_plot<-ggmap(get_map(location=center,zoom=16,maptype='toner'))
ny_plot + geom_point(x= -73.96457, y= 40.80993, color="red")

I'm using:
ggmap version 2.4
ggplot version 1.01
R version 3.1.3

**Comment by dkahle** [comment]
Fixed but never closed. Thanks!
