### ISSUE TITLE
geocode() unable to connect - datasciencetoolkit.org down

### ISSUE THREAD

**Issue by katerabinowitz** [dkahle/ggmap#73]
The geocode function in ggmap relies on the datasciencetoolkit.org to use the Google Maps API. However, datasciencetoolkit.org is down. Based on creator Pete Warden's post in late September - http://petewarden.com/2015/09/27/openheatmap-and-datasciencetoolkit-under-new-management/ - the site may be down for good. 

Since Thursday running geocode() has resulted in errors like this:
Warning messages:
1: In readLines(connect, warn = FALSE) :
  unable to connect to 'www.datasciencetoolkit.org' on port 80.
2: In FUN(X[[i]], ...) :
    geocoding failed for "0 13TH ST NE, Washington DC".
  if accompanied by 500 Internal Server Error with using dsk, try google.

**Comment by geobrando** [comment]
Hi @katerabinowitz.  This is clearly an issue.  It will be interesting to see how this shakes out and if the new team plan to keep this service running or if there is an alternative instance running somewhere that can be used.  But the dstk geocoding api and the google maps geocoding api are separate services and `geocode()` can use either one.  This can be used by calling `geocode(location,source="google")`.

**Comment by dkahle** [comment]
(Sorry for not posting.) A while back I changed the default back to Google for this reason. DSK seems to be working better now than then. I'm going to go ahead and close the issue, but if there is more to it, please do let me know! Thanks!
