### ISSUE TITLE
geom_polygon incorrect at specific zoom levels 

### ISSUE THREAD

**Issue by peekxc** [dkahle/ggmap#74]
When using geom_polygon with ggmap, polygons that are drawn onto the map are incorrect if the initial zoom level is too small (far away). 

Reproducible example code that produces a correct polygon: 

<div style="overflow:auto;"><div class="geshifilter"><pre class="r geshifilter-R" style="font-family:monospace;">longitude <span style="">&lt;-</span> <a href="http://inside-r.org/r-doc/base/c"><span style="color: #003399; font-weight: bold;">c</span></a><span style="color: #009900;">&#40;</span><span style="">-</span><span style="color: #cc66cc;">83.01422</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01429</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01468</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01466</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01377</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01331</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01285</span><span style="color: #009900;">&#41;</span>
latitude <span style="">&lt;-</span> <a href="http://inside-r.org/r-doc/base/c"><span style="color: #003399; font-weight: bold;">c</span></a><span style="color: #009900;">&#40;</span><span style="color: #cc66cc;">39.98964</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.98962</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99023</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99031</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99068</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99061</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99026</span><span style="color: #009900;">&#41;</span>
coordinates <span style="">&lt;-</span> <a href="http://inside-r.org/r-doc/base/data.frame"><span style="color: #003399; font-weight: bold;">data.frame</span></a><span style="color: #009900;">&#40;</span>longitude<span style="color: #339933;">,</span> latitude<span style="color: #009900;">&#41;</span>
mapImageData <span style="">&lt;-</span> ggmap<span style="">::</span>get_map<span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/c"><span style="color: #003399; font-weight: bold;">c</span></a><span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/mean"><span style="color: #003399; font-weight: bold;">mean</span></a><span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/range"><span style="color: #003399; font-weight: bold;">range</span></a><span style="color: #009900;">&#40;</span>longitude<span style="color: #009900;">&#41;</span><span style="color: #009900;">&#41;</span><span style="color: #339933;">,</span> <a href="http://inside-r.org/r-doc/base/mean"><span style="color: #003399; font-weight: bold;">mean</span></a><span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/range"><span style="color: #003399; font-weight: bold;">range</span></a><span style="color: #009900;">&#40;</span>latitude<span style="color: #009900;">&#41;</span><span style="color: #009900;">&#41;</span><span style="color: #009900;">&#41;</span><span style="color: #339933;">,</span> zoom=<span style="color: #cc66cc;">15</span><span style="color: #009900;">&#41;</span>
map <span style="">&lt;-</span> ggmap<span style="">::</span>ggmap<span style="color: #009900;">&#40;</span>mapImageData<span style="color: #009900;">&#41;</span>
map <span style="">&lt;-</span> map <span style="">+</span> <a href="http://inside-r.org/packages/cran/ggplot2"><span style="">ggplot2</span></a><span style="">::</span>geom_polygon<span style="color: #009900;">&#40;</span><a href="http://inside-r.org/packages/cran/ggplot2"><span style="">ggplot2</span></a><span style="">::</span>aes<span style="color: #009900;">&#40;</span>x=longitude<span style="color: #339933;">,</span> y=latitude<span style="color: #009900;">&#41;</span><span style="color: #339933;">,</span> <a href="http://inside-r.org/r-doc/utils/data"><span style="color: #003399; font-weight: bold;">data</span></a>=coordinates<span style="color: #009900;">&#41;</span>
<a href="http://inside-r.org/r-doc/graphics/plot"><span style="color: #003399; font-weight: bold;">plot</span></a><span style="color: #009900;">&#40;</span>map<span style="color: #009900;">&#41;</span></pre></div></div>

The same code that produces an incorrect polygon (might need to zoom in to see): 

<div style="overflow:auto;"><div class="geshifilter"><pre class="r geshifilter-R" style="font-family:monospace;">longitude <span style="">&lt;-</span> <a href="http://inside-r.org/r-doc/base/c"><span style="color: #003399; font-weight: bold;">c</span></a><span style="color: #009900;">&#40;</span><span style="">-</span><span style="color: #cc66cc;">83.01422</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01429</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01468</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01466</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01377</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01331</span><span style="color: #339933;">,</span> <span style="">-</span><span style="color: #cc66cc;">83.01285</span><span style="color: #009900;">&#41;</span>
latitude <span style="">&lt;-</span> <a href="http://inside-r.org/r-doc/base/c"><span style="color: #003399; font-weight: bold;">c</span></a><span style="color: #009900;">&#40;</span><span style="color: #cc66cc;">39.98964</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.98962</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99023</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99031</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99068</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99061</span><span style="color: #339933;">,</span> <span style="color: #cc66cc;">39.99026</span><span style="color: #009900;">&#41;</span>
coordinates <span style="">&lt;-</span> <a href="http://inside-r.org/r-doc/base/data.frame"><span style="color: #003399; font-weight: bold;">data.frame</span></a><span style="color: #009900;">&#40;</span>longitude<span style="color: #339933;">,</span> latitude<span style="color: #009900;">&#41;</span>
mapImageData <span style="">&lt;-</span> ggmap<span style="">::</span>get_map<span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/c"><span style="color: #003399; font-weight: bold;">c</span></a><span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/mean"><span style="color: #003399; font-weight: bold;">mean</span></a><span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/range"><span style="color: #003399; font-weight: bold;">range</span></a><span style="color: #009900;">&#40;</span>longitude<span style="color: #009900;">&#41;</span><span style="color: #009900;">&#41;</span><span style="color: #339933;">,</span> <a href="http://inside-r.org/r-doc/base/mean"><span style="color: #003399; font-weight: bold;">mean</span></a><span style="color: #009900;">&#40;</span><a href="http://inside-r.org/r-doc/base/range"><span style="color: #003399; font-weight: bold;">range</span></a><span style="color: #009900;">&#40;</span>latitude<span style="color: #009900;">&#41;</span><span style="color: #009900;">&#41;</span><span style="color: #009900;">&#41;</span><span style="color: #339933;">,</span> zoom=<span style="color: #cc66cc;">14</span><span style="color: #009900;">&#41;</span>
map <span style="">&lt;-</span> ggmap<span style="">::</span>ggmap<span style="color: #009900;">&#40;</span>mapImageData<span style="color: #009900;">&#41;</span>
map <span style="">&lt;-</span> map <span style="">+</span> <a href="http://inside-r.org/packages/cran/ggplot2"><span style="">ggplot2</span></a><span style="">::</span>geom_polygon<span style="color: #009900;">&#40;</span><a href="http://inside-r.org/packages/cran/ggplot2"><span style="">ggplot2</span></a><span style="">::</span>aes<span style="color: #009900;">&#40;</span>x=longitude<span style="color: #339933;">,</span> y=latitude<span style="color: #009900;">&#41;</span><span style="color: #339933;">,</span> <a href="http://inside-r.org/r-doc/utils/data"><span style="color: #003399; font-weight: bold;">data</span></a>=coordinates<span style="color: #009900;">&#41;</span>
<a href="http://inside-r.org/r-doc/graphics/plot"><span style="color: #003399; font-weight: bold;">plot</span></a><span style="color: #009900;">&#40;</span>map<span style="color: #009900;">&#41;</span></pre></div></div>

**Comment by restonslacker** [comment]
is this still an issue?  i added `+ coord_map(xlim=c(-83.015,-83.012), ylim=c(39.989,39.991))` to both maps in your examples and i'm having a difficult time seeing the differences.  if it is still an issue can you elaborate on what you expect to see and what is not working correctly?

Zoom level 15:
![map_zoom15](https://cloud.githubusercontent.com/assets/5813515/17974398/ef82de30-6ab3-11e6-8bc6-d0689ca9ff1c.png)

Zoom level 14:
![map_zoom14](https://cloud.githubusercontent.com/assets/5813515/17974399/ef8380c4-6ab3-11e6-844e-500e4e7d2c0e.png)

**Comment by dkahle** [comment]
That's a lot of scope resolution'ing. :)

But same here, things look the same to me with the following code:
```{r}
library(ggmap)

longitude <- c(-83.01422, -83.01429, -83.01468, -83.01466, -83.01377, -83.01331, -83.01285)
latitude <- c(39.98964, 39.98962, 39.99023, 39.99031, 39.99068, 39.99061, 39.99026)
coordinates  <- data.frame(longitude, latitude)


mapImageData <- get_map(c(mean(range(longitude)), mean(range(latitude))), zoom=15)
ggmap(mapImageData) + 
  geom_polygon(aes(x=longitude, y=latitude), data=coordinates)


mapImageData <- get_map(c(mean(range(longitude)), mean(range(latitude))), zoom=14)
ggmap(mapImageData) + 
  geom_polygon(aes(x=longitude, y=latitude), data=coordinates)
```

I'm going to go ahead and close it; if it remains a problem let me know. Thanks!
