### ISSUE TITLE
source="cloudmade" and maptype = "terrain", source="stamen"

### ISSUE THREAD

**Issue by ckluss** [dkahle/ggmap#75]
Hi

thx for the great package. I think the "cloudmade" service is down and stamen:terrain does not work any more :(

Best wishes
Christof

**Comment by ckluss** [comment]
oh, it is only available in the USA http://maps.stamen.com  ... but cloudmade seems not to work

**Comment by dkahle** [comment]
Right. Cloudmade is deprecated now and Stamen just came out with global terrain maps. Thanks!
