### ISSUE TITLE
when specifying Client  & Signature doesn't concatenate to url geocode.R

### ISSUE THREAD

**Issue by countershane** [dkahle/ggmap#76]
Checking for presence of client & signature works, but when specified, is not added to the geocode request url.

**Comment by dkahle** [comment]
Can you try an example with the dev version? To install it, type
```r
devtools::install_github("dkahle/ggmap")
```
Thanks!

**Comment by scottmmjackson** [comment]
Please update if the issue still exists after updating to the latest.
