### ISSUE TITLE
qmplot Error: object '.all_aesthetics' not found

### ISSUE THREAD

**Issue by Hughan** [dkahle/ggmap#81]
Executing the qmplot example on the GitHub repository home page:
```R
library(ggmap)
downtown <- subset(crime,
                   -95.39681 <= lon & lon <= -95.34188 &
                     29.73631 <= lat & lat <=  29.78400
)

qmplot(lon, lat, data = downtown, maptype = "toner-background", color = I("red"))
```
yields the error:
```R
Error in unlist(.all_aesthetics[1:42]) : 
  object '.all_aesthetics' not found
```
Version info;
* R: R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
* ggmap: Both 2.6 and 2.6.999 (installed from github, GithubSHA1: 957bd583b5faff1bc9ed798689af2922ebcd9204)

**Comment by dkahle** [comment]
Ugh, awful.  Thanks!
