### ISSUE TITLE
Using a personalized API key in geocode

### ISSUE THREAD

**Issue by LucasPuente** [dkahle/ggmap#83]
The `geocode` function doesn't allow users to use their personalized API key. If it did, the API limit could go from 2,500 requests / day to 100,000 / day.

**Comment by tyokota** [comment]
If you need a quick workaround, take the geocode.R from this repo and replace the following lines to accommodate your API key.

```
  if(source == "google"){
    url_string <- paste("http://maps.googleapis.com/maps/api/geocode/json?address=", posturl, sep = "")
  } else if(source == "dsk"){
    url_string <- paste("http://www.datasciencetoolkit.org/maps/api/geocode/json?address=", posturl, sep = "")
  }
```

inserting Google API into string
```
  if(source == "google"){
    url_string <- paste("http://maps.googleapis.com/maps/api/geocode/json?address=", posturl, "&key=xxx", sep = "")
  } else if(source == "dsk"){
    url_string <- paste("http://www.datasciencetoolkit.org/maps/api/geocode/json?address=", posturl, sep = "")
  }
```

Ideally, a means of including a key from the package scripts would be preferred.

`    url_string <- paste("http://maps.googleapis.com/maps/api/geocode/json?address=", posturl, "&key=", googlekey, sep = "")`

**Comment by LucasPuente** [comment]
Good thinking. I had a similar thought: http://stackoverflow.com/questions/34402979/increase-the-api-limit-in-ggmaps-geocode-function-in-r/34405181#34405181. Thanks for sharing your idea.

**Comment by cronacronis** [comment]
Why not as a parameter to `geocode()`?

**Comment by washcycle** [comment]
@cronacronis I think that is the idea. I cloned a copy to do this and that is what I did, added an `apikey` parameter to `geocode()`. There is a pull request #94 that implements this too, but it is still open.

**Comment by dkahle** [comment]
I'm actually overhauling this right now.  Should be done soon...

**Comment by dkahle** [comment]
Got it. Thanks, all!

**Comment by dkahle** [comment]
No, not yet. Hoping to push a release to CRAN soon though for __ggplot2__ 2.3.0, so stay tuned!

**Comment by fvalenduc** [comment]
geocode now always fails with "over the query limut" with google, even for the first query of the day. It is probably linked with the new pricing policy of google. So allowing to use an API key easily would be helpful. I tried to find the place in the code to apply the workaround described here above, but I doesn't find it. Has the code changed since 2016 ?

**Comment by dkahle** [comment]
Try 
```r
if(!requireNamespace("devtools")) install.packages("devtools")
devtools::install_github("dkahle/ggmap", ref = "tidyup"
```
Then setup credentials. Details can be found at #51.
