### ISSUE TITLE
Suddenly having problems with gglocator

### ISSUE THREAD

**Issue by teemo48** [dkahle/ggmap#87]
Was working fine.  Installed some new versions of various packages
Now get 
"Error in grid.Call.graphics(L_downviewport, name$name, strict) : 
  Viewport 'NA' was not found"
# Mac OS X
# R 3.2.2
# ggmap_2.6.1
# ggplot2_2.1.0
# Example from ?gglocator

> if(interactive()){
> -     # only run for interactive sessions
> -   
> -     df <- expand.grid(x = 0:-5, y = 0:-5)
> -     (p <- qplot(x, y, data = df) +
> -         annotate(geom = 'point', x = -2, y = -2, colour = 'red'))
> -     gglocator()
> -   
> -     p +
> -         scale_x_continuous(expand = c(0,0)) +
> -         scale_y_continuous(expand = c(0,0))
> -     gglocator(1, xexpand = c(0,0), yexpand = c(0,0))
> - }
>   Error in grid.Call.graphics(L_downviewport, name$name, strict) : 
>   Viewport 'NA' was not found

**Comment by salah31416** [comment]
gglocator.R
line 53: x <- x[grep("panel.", x)][1]
change
x <- x[grep("layout", x)][1]

**Comment by teemo48** [comment]
Thanks!  Had forgotten all about it, but going to have to do some mapping in coming months.  So I appreciate it!

**Comment by jan-glx** [comment]
@salah31416 , are you sure? while it shows no error and returns values, the results seem scaled for me when applying your patch

**Comment by dkahle** [comment]
Yea, still bugged.... :/

**Comment by dkahle** [comment]
@hadley, is there a simple fix to this problem?  Looking for a simple mapping from the output of `grid.locator("npc")` to the data space. `layer_scales(last_plot())$x$range$range` and the expanded version `plot_info$layout$panel_ranges[[1]]$x.range` (and their `y` counterparts) don't seem to do it when rescaled... and I would imagine that wouldn't work for nonlinear scalings anyway.

Here's a simple example:
```{r}
df <- expand.grid(x = 0:-5, y = 0:-5)
qplot(x, y, data = df) +
  annotate(geom = "point", x = -2, y = -2, colour = "red")
(pt <- gglocator()) # click red point
last_plot() +
  annotate("point", pt$x, pt$y, color = "blue", size = 3, alpha = .5)
```

**Comment by hadley** [comment]
Maybe see what @wch did for shiny?

**Comment by wch** [comment]
Here are the chnages I made for Shiny:
https://github.com/rstudio/shiny/commit/24e812324042a8ac932606b0c9d68e67f6954dfa

**Comment by dkahle** [comment]
Great, I'll have a look. Thanks guys!

**Comment by elbamos** [comment]
Guys is there a workaround on this for the time being?

**Comment by e-larry** [comment]
I am new to ggmap, and was following the "ggmap in action" example in @dkahle 's [ggmap paper in 2013](https://journal.r-project.org/archive/2013-1/kahle-wickham.pdf). I ran into the same problem as the OP when executing `gglocator(2)`. Is this problem resolved?
