### ISSUE TITLE
google api key

### ISSUE THREAD

**Issue by spedygiorgio** [dkahle/ggmap#92]
It would be useful to add the google api key to the ggmap package, maybe recycling the api_key used for cloudmate...

**Comment by amormachine** [comment]
I second this request, which also appears to be duplicated in #29.  In the interim, there appears to be a viable workaround described on StackOverflow:

[Workaround](http://stackoverflow.com/questions/34402979/increase-the-api-limit-in-ggmaps-geocode-function-in-r)

**Comment by emraher** [comment]
Third on this one.

**Comment by nickeubank** [comment]
+1

**Comment by joshmwolff** [comment]
Agreed. I'm using ggmap's route function to get a bunch of driving times. ggmap is such an awesome R package, but it really needs to be able to connect to a Google API key. Thanks!

**Comment by SymbolixAU** [comment]
I've written the package [googleway](https://github.com/SymbolixAU/googleway) to access Google Maps API using an API Key. Maybe this is of help?

**Comment by dkahle** [comment]
This has been fixed with the `register_google()` function. I've implemented a way for most Google functions already, more to come soon.  Thanks all!

**Comment by spedygiorgio** [comment]
great

**Comment by ehartford** [comment]
how do i use it?  It's not mentioned in the CRAN docs
