### ISSUE TITLE
route(): straight lines instead of following roads

### ISSUE THREAD

**Issue by rjake** [dkahle/ggmap#99]
There are a lot of people who want to be able to replicate ArcMap's network analyst and the ggmap ```route()``` function is a huge step in that direction. It generates the correct road coordinates but then draws straight lines between the points when I try to plot them. Is there a way a polyline function could be built to put the path on the roads? 

The yellow lines on this map show where I want the lines to be, however, the plot is showing straight lines instead.
![wronglines](https://cloud.githubusercontent.com/assets/14003618/16358939/e9c46010-3af0-11e6-855c-683085162ac4.png)

This forum points me in the right direction: 
http://stackoverflow.com/questions/30270011/ggmap-route-finding-doesnt-stay-on-roads

Unfortunately, I cannot figure out how to put it into a for-loop to get multiple routes as well as the distance of each leg/total distance. 

I hope something like this can be implemented in the future; beautiful data vizzes await!

**Comment by dkahle** [comment]
(Note for future)
[https://developers.google.com/maps/documentation/utilities/polylinealgorithm](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
